# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


set(CPACK_BINARY_DEB "OFF")
set(CPACK_BINARY_FREEBSD "OFF")
set(CPACK_BINARY_IFW "OFF")
set(CPACK_BINARY_NSIS "OFF")
set(CPACK_BINARY_RPM "OFF")
set(CPACK_BINARY_STGZ "ON")
set(CPACK_BINARY_TBZ2 "OFF")
set(CPACK_BINARY_TGZ "ON")
set(CPACK_BINARY_TXZ "OFF")
set(CPACK_BINARY_TZ "ON")
set(CPACK_BUILD_SOURCE_DIRS "/home/jco/builds/Gridcoin-Research/.claude/worktrees/gui-interfaces-1c1;/home/jco/builds/Gridcoin-Research/.claude/worktrees/gui-interfaces-1c1/build_tsa")
set(CPACK_CMAKE_GENERATOR "Unix Makefiles")
set(CPACK_COMPONENTS_ALL "daemon;gui")
set(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
set(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
set(CPACK_COPYRIGHT_STRING "Copyright (C) 2014-2026 The Gridcoin developers")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_DEFAULT_PACKAGE_DESCRIPTION_SUMMARY "Gridcoin built using CMake")
set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE "ON")
set(CPACK_DMG_VOLUME_NAME "Gridcoin")
set(CPACK_GENERATOR "STGZ;TGZ;TZ")
set(CPACK_ICONDIR "/home/jco/builds/Gridcoin-Research/.claude/worktrees/gui-interfaces-1c1/share/pixmaps")
set(CPACK_INNOSETUP_ARCHITECTURE "x64")
set(CPACK_INSTALL_CMAKE_PROJECTS "/home/jco/builds/Gridcoin-Research/.claude/worktrees/gui-interfaces-1c1/build_tsa;Gridcoin;ALL;/")
set(CPACK_INSTALL_PREFIX "/usr/local")
set(CPACK_MODULE_PATH ";/home/jco/builds/Gridcoin-Research/.claude/worktrees/gui-interfaces-1c1/build-aux/cpack")
set(CPACK_NSIS_DISPLAY_NAME "GridcoinResearch")
set(CPACK_NSIS_INSTALLER_ICON_CODE "")
set(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
set(CPACK_NSIS_PACKAGE_NAME "Gridcoin")
set(CPACK_NSIS_UNINSTALL_NAME "Uninstall")
set(CPACK_OBJCOPY_EXECUTABLE "/usr/bin/llvm-objcopy")
set(CPACK_OBJDUMP_EXECUTABLE "/usr/bin/llvm-objdump")
set(CPACK_OUTPUT_CONFIG_FILE "/home/jco/builds/Gridcoin-Research/.claude/worktrees/gui-interfaces-1c1/build_tsa/CPackConfig.cmake")
set(CPACK_PACKAGE_CHECKSUM "SHA256")
set(CPACK_PACKAGE_CONTACT "Gridcoin Developers <dev@gridcoin.us>")
set(CPACK_PACKAGE_DEFAULT_LOCATION "/")
set(CPACK_PACKAGE_DESCRIPTION_FILE "/usr/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "Gridcoin Research Wallet")
set(CPACK_PACKAGE_FILE_NAME "gridcoinresearch-5.5.1.4-x86_64")
set(CPACK_PACKAGE_HOMEPAGE_URL "https://gridcoin.us")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "GridcoinResearch")
set(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "GridcoinResearch")
set(CPACK_PACKAGE_NAME "Gridcoin")
set(CPACK_PACKAGE_RELOCATABLE "true")
set(CPACK_PACKAGE_VENDOR "The Gridcoin Community")
set(CPACK_PACKAGE_VERSION "5.5.1.4")
set(CPACK_PACKAGE_VERSION_MAJOR "5")
set(CPACK_PACKAGE_VERSION_MINOR "5")
set(CPACK_PACKAGE_VERSION_PATCH "1")
set(CPACK_PACKAGE_VERSION_TWEAK "4")
set(CPACK_PROJECT_CONFIG_FILE "/home/jco/builds/Gridcoin-Research/.claude/worktrees/gui-interfaces-1c1/build_tsa/CPackOptions.cmake")
set(CPACK_READELF_EXECUTABLE "/usr/bin/llvm-readelf")
set(CPACK_RESOURCE_FILE_CHANGELOG "/home/jco/builds/Gridcoin-Research/.claude/worktrees/gui-interfaces-1c1/CHANGELOG.md")
set(CPACK_RESOURCE_FILE_LICENSE "/home/jco/builds/Gridcoin-Research/.claude/worktrees/gui-interfaces-1c1/COPYING")
set(CPACK_RESOURCE_FILE_README "/usr/share/cmake/Templates/CPack.GenericDescription.txt")
set(CPACK_RESOURCE_FILE_WELCOME "/usr/share/cmake/Templates/CPack.GenericWelcome.txt")
set(CPACK_SET_DESTDIR "OFF")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;TXZ;TZ")
set(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/jco/builds/Gridcoin-Research/.claude/worktrees/gui-interfaces-1c1/build_tsa/CPackSourceConfig.cmake")
set(CPACK_SOURCE_PACKAGE_FILE_NAME "gridcoinresearch-5.5.1.4")
set(CPACK_SOURCE_RPM "OFF")
set(CPACK_SOURCE_TBZ2 "ON")
set(CPACK_SOURCE_TGZ "ON")
set(CPACK_SOURCE_TXZ "ON")
set(CPACK_SOURCE_TZ "ON")
set(CPACK_SOURCE_ZIP "OFF")
set(CPACK_STRIP_FILES "ON")
set(CPACK_SYSTEM_NAME "x86_64")
set(CPACK_THREADS "1")
set(CPACK_TOPLEVEL_TAG "x86_64")
set(CPACK_WINDOWS_BITS "64")
set(CPACK_WIX_SIZEOF_VOID_P "8")

if(NOT CPACK_PROPERTIES_FILE)
  set(CPACK_PROPERTIES_FILE "/home/jco/builds/Gridcoin-Research/.claude/worktrees/gui-interfaces-1c1/build_tsa/CPackProperties.cmake")
endif()

if(EXISTS ${CPACK_PROPERTIES_FILE})
  include(${CPACK_PROPERTIES_FILE})
endif()
