

#include <QtGlobal>

// Automatically generated by extract_strings_qt.py
#ifdef __GNUC__
#define UNUSED __attribute__((unused))
#else
#define UNUSED
#endif
static const char UNUSED *bitcoin_strings[] = {
QT_TRANSLATE_NOOP("bitcoin-core", "Gridcoin"),
QT_TRANSLATE_NOOP("bitcoin-core", "The %s developers"),
QT_TRANSLATE_NOOP("bitcoin-core", "The Gridcoin developers"),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"%s, you must set a rpcpassword in the configuration file:\n"
" %s\n"
"It is recommended you use the following random password:\n"
"rpcuser=gridcoinrpc\n"
"rpcpassword=%s\n"
"(you do not need to remember this password)\n"
"The username and password MUST NOT be the same.\n"
"If the file does not exist, create it with owner-readable-only file "
"permissions.\n"
"It is also recommended to set alertnotify so you are notified of problems;\n"
"for example: alertnotify=echo %%s | mail -s \"Gridcoin Alert\" admin@foo."
"com\n"),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"-rpcssl is no longer supported, and -rpcconnect=%s does not resolve to a "
"loopback address. Sending RPC credentials to it would transmit them "
"unencrypted. Remove -rpcssl to proceed deliberately, and tunnel the "
"connection (for example over SSH) if it crosses an untrusted network."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"A poll with a yes/no/abstain response type cannot include any additional "
"custom choices."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"An error occurred while setting up the RPC port %u for listening on %s: %s"),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"An error occurred while setting up the RPC port %u for listening on IPv4: %s"),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"An error occurred while setting up the RPC port %u for listening on IPv6, "
"falling back to IPv4: %s"),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Block file corruption detected and automatic recovery failed. Please restart "
"with -reindex to rebuild the chain state."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Cannot access the data directory; check that it exists and that you have "
"permission to read and write it."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Cannot obtain a lock on data directory %s. %s is probably already running "
"and using that directory."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Cannot obtain a lock on data directory %s. %s is probably already running."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Check that BOINC is installed and that you have the correct path in the "
"config file if you installed it to a nonstandard location."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Due to the failure to delete the blockchain data you will be required to "
"manually delete the data before starting your wallet."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"ERROR: Block index integrity check failed: Blockchain data may be "
"corrupted.\n"
"\n"
"Gridcoin detected a block index entry with a broken pprev linkage. This may "
"occur because of a late software upgrade, unexpected exit, or a power "
"failure that left the on-disk block index database in an inconsistent state. "
"Please run gridcoinresearchd with the -resetblockchaindata parameter. Your "
"wallet will re-download the blockchain. Your balance may appear incorrect "
"until the synchronization finishes."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"ERROR: Block index integrity check failed: Blockchain data may be "
"corrupted.\n"
"\n"
"Gridcoin detected a block index entry with a broken pprev linkage. This may "
"occur because of a late software upgrade, unexpected exit, or a power "
"failure that left the on-disk block index database in an inconsistent state. "
"Your blockchain data is being reset and your wallet will resync from genesis "
"when you restart. Your balance may appear incorrect until the "
"synchronization finishes."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"ERROR: Checkpoint mismatch: Blockchain data may be corrupted.\n"
"\n"
"Gridcoin's compiled-in hardened checkpoint does not match the block at that "
"height in your local block index. This may occur because of a late software "
"upgrade, unexpected exit, or a power failure. Please run gridcoinresearchd "
"with the -resetblockchaindata parameter. Your wallet will re-download the "
"blockchain. Your balance may appear incorrect until the synchronization "
"finishes."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"ERROR: Checkpoint mismatch: Blockchain data may be corrupted.\n"
"\n"
"Gridcoin's compiled-in hardened checkpoint does not match the block at that "
"height in your local block index. This may occur because of a late software "
"upgrade, unexpected exit, or a power failure. Your blockchain data is being "
"reset and your wallet will resync from genesis when you restart. Your "
"balance may appear incorrect until the synchronization finishes."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Error initializing database environment %s! To recover, BACKUP THAT "
"DIRECTORY, then remove everything from it except for wallet.dat."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Error: Clock skew is 5 minutes or greater. Please check your clock settings."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Error: The mandatory sidestake transaction was rejected. There is already a "
"mandatory sidestake transaction in the mempool. Wait until that transaction "
"is bound in a block."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Error: The transaction was rejected.  This might happen if some of the coins "
"in your wallet were already spent, such as if you used a copy of wallet.dat "
"and coins were spent in the copy but not marked as spent here."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Error: The transaction was rejected. This might happen if some of the coins "
"in your wallet were already spent, such as if you used a copy of wallet.dat "
"and coins were spent in the copy but not marked as spent here."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Error: This transaction requires a transaction fee of at least %s because of "
"its amount, complexity, or use of recently received funds  "),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Error: This transaction requires a transaction fee of at least %s because of "
"its amount, complexity, or use of recently received funds "),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Error: Unsupported argument -socks found. Setting SOCKS version isn't "
"possible anymore, only SOCKS5 proxies are supported."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Failed: 80 block difficulty is less than %1. This wallet is almost certainly "
"forked."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Failure to do so will result in undefined behaviour or failure to start "
"wallet."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"For initiatives related to the Gridcoin community not covered by other poll "
"types."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"For polls about community representation, public relations, and "
"communications."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Gridcoin detected a multi-superblock chain reorganization and is rebuilding "
"the beacon registry to maintain consensus with the network. The wallet may "
"be briefly unresponsive while the rebuild runs."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"No single address can attest to %s GRC in %u or fewer UTXOs. Consider "
"consolidating UTXOs."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Please check your network and also check the config file and ensure your "
"addnode entries are up-to-date. If you recently started the wallet, you may "
"want to wait another few minutes for connections to build up and test again. "
"Please see https://gridcoin.us/wiki/config-file.html and https://addnodes."
"cycy.me/."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Please ensure that you have followed the process to advertise and verify "
"your beacon. You can use the research wizard (the beacon button on the "
"overview screen)."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Poll additional field value \"%s\" for field name \"%s\" exceeds %s "
"characters."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Proposals related to Gridcoin management like poll requirements and funding."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Propose additions or removals of computing projects for research reward "
"eligibility."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"The IP for the port test site is unable to be resolved. This could mean your "
"DNS is not working correctly. The wallet may operate without DNS, but it "
"could be severely degraded, especially if the wallet is new and a database "
"of prior successful connections has not been built up. Please check your "
"computer and ensure name resolution is operating correctly."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"The connection to the port test site was refused. This could be a transient "
"problem with the port test site, but could also be an issue with your "
"firewall. If you are also failing the connection test, your firewall is most "
"likely blocking network communications from the Gridcoin client."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"The data directory path '%s' contains characters that cannot be represented "
"in the system code page, and Windows 8.3 short filename generation is not "
"available on this volume. Please choose a data directory path using only "
"characters supported by your system locale, or enable 8.3 filename "
"generation."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"The default data directory is on a temporary filesystem, so the block chain "
"and wallet would be lost when the program exits. Pass -datadir with a "
"location on persistent storage."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"The network has experienced a low-level error and this probably means your "
"IP address or other network connection parameters are not configured "
"correctly. Please check your network configuration on your computer."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"The network is reporting an unspecified socket error. If you also are "
"failing the connection test, then please check your computer's network "
"configuration."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"The port test site is closed on port. This could be a transient problem with "
"the port test site, but could also be an issue with your firewall. If you "
"are also failing the connection test, your firewall is most likely blocking "
"network communications from the Gridcoin client."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"The wallet has less than five connections to the network and is unable to "
"connect to an NTP server to check your computer clock. This is not "
"necessarily a problem. You can wait a few minutes and try the test again."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"The wallet will now shutdown. Please start your wallet to begin sync from "
"zero"),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"There is a new leisure version available and you should upgrade as soon as "
"practical."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"There is a new mandatory version available and you should upgrade as soon as "
"possible to ensure your wallet remains in consensus with the network."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Unable to bind to %s on this computer. Gridcoin is probably already running."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Verify (1) that you have BOINC installed correctly, (2) that you have "
"attached at least one whitelisted project, (3) that you advertised your "
"beacon with the same email as you use for your BOINC project(s), and (4) "
"that the CPID on the overview screen matches the CPID when you login to your "
"BOINC project(s) online."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Verify that you have actually completed workunits for the projects you have "
"attached and that you have authorized the export of statistics. Please see "
"https://gridcoin.us/guides/whitelist.htm."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"WARNING: A mandatory release is available. Please upgrade as soon as "
"possible."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"WARNING: You are running a version that is higher than the latest release."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Warning: -paytxfee is set very high! This is the transaction fee you will "
"pay if you send a transaction."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Warning: 80 block difficulty is less than %1. This wallet is probably forked."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Warning: Clock skew is between 3 and 5 minutes. Please check your clock "
"settings."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Warning: ETTS is > 90 days. It will take a very long time to receive your "
"research rewards by staking - increase balance or use MRC"),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Warning: ETTS is infinite. No coins to stake - increase balance or use MRC"),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Warning: Please check that your computer's date and time are correct! If "
"your clock is wrong Gridcoin will not work properly."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Warning: error reading wallet.dat! All keys read correctly, but transaction "
"data or address book entries might be missing or incorrect."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Warning: wallet.dat corrupt, data salvaged! Original wallet.dat saved as "
"wallet.{timestamp}.bak in %s; if your balance or transactions are incorrect "
"you should restore from a backup."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"You have no balance and will be unable to retrieve your research rewards "
"when solo crunching by staking. You can use MRC to retrieve your rewards, or "
"you should acquire GRC to stake so you can retrieve your research rewards. "
"Please see https://gridcoin.us/guides/boinc-install.htm."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"You must set rpcpassword=<password> in the configuration file:\n"
"%s\n"
"If the file does not exist, create it with owner-readable-only file "
"permissions."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"You will not be able to stake because you have less than %1 connection(s). "
"Please check your network and also check the config file and ensure your "
"addnode entries are up-to-date. If you recently started the wallet, you may "
"want to wait another few minutes for connections to build up and then test "
"again. Please see https://gridcoin.us/wiki/config-file.html and https://"
"addnodes.cycy.me/."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Your balance is low given the current network difficulty to stake in a "
"reasonable period of time to retrieve your research rewards when solo "
"crunching. You should consider acquiring more GRC to stake more often, or "
"else use MRC to retrieve your rewards."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Your balance is too low given the current network difficulty to stake in a "
"reasonable period of time to retrieve your research rewards when solo "
"crunching. You can use MRC  to retrieve your rewards, or you should acquire "
"more GRC to stake more often."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Your clock in your computer is significantly off from UTC or network time "
"and this may seriously degrade the operation of the wallet, including "
"maintaining connection to the network. You should check your time and time "
"zone settings for your computer. A very common problem is the off by one "
"hour caused by a time zone issue or problems with daylight savings time."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Your difficulty is extremely low and your wallet is almost certainly forked. "
"Please ensure you are running the latest version and try removing the "
"blockchain database and resyncing from genesis using the menu option. (Note "
"this will take 2-4 hours.)"),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Your difficulty is low but your wallet is still in initial sync. Please "
"recheck it later to see if this passes."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Your difficulty is very low and your wallet is probably forked. Please "
"ensure you are running the latest version and try removing the blockchain "
"database and resyncing from genesis using the menu option. (Note this will "
"take 2-4 hours.)"),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Your outbound connection count is critically low. Please check your the "
"config file and ensure your addnode entries are up-to-date. If you recently "
"started the wallet, you may want to wait another few minutes for connections "
"to build up and then test again. Please see https://gridcoin.us/wiki/config-"
"file.html and https://addnodes.cycy.me/."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Your outbound connection count is low. Please check your the config file and "
"ensure your addnode entries are up-to-date. If you recently started the "
"wallet, you may want to wait another few minutes for connections to build up "
"and then test again. Please see https://gridcoin.us/wiki/config-file.html "
"and https://addnodes.cycy.me/."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Your wallet is not in sync and has not previously been in sync during this "
"run, please wait for the wallet to sync and retest. If there are other "
"failures preventing the wallet from syncing, please correct those items and "
"retest to see if this test passes."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Your wallet is out of sync with the network but was in sync before. If this "
"fails there is likely a severe problem that is preventing the wallet from "
"syncing. If the lack of sync is due to network connection issues, you will "
"see failures on the network connection test(s). If the network connections "
"pass, but your wallet fails this test, and continues to fail this test on "
"repeated attempts with a few minutes in between, this could indicate a more "
"serious issue. In that case you should check the debug log to see if it "
"sheds light on the cause for no sync."),
QT_TRANSLATE_NOOP("bitcoin-core", ""
"Your wallet is still in initial sync. If this is a sync from the beginning "
"(genesis), the sync process can take from 2 to 4 hours, or longer on a slow "
"computer. If you have synced your wallet before but you just started the "
"wallet up, then wait a few more minutes and retry the diagnostics again."),
QT_TRANSLATE_NOOP("bitcoin-core", "-maxmempool must be between %d and %d MB."),
QT_TRANSLATE_NOOP("bitcoin-core", "A poll choice cannot be empty."),
QT_TRANSLATE_NOOP("bitcoin-core", "Active by Greylist Override"),
QT_TRANSLATE_NOOP("bitcoin-core", "Active"),
QT_TRANSLATE_NOOP("bitcoin-core", "Authorized"),
QT_TRANSLATE_NOOP("bitcoin-core", "Automatically Greylisted"),
QT_TRANSLATE_NOOP("bitcoin-core", "Balance too low to create a contract."),
QT_TRANSLATE_NOOP("bitcoin-core", "Balance"),
QT_TRANSLATE_NOOP("bitcoin-core", "Block Version"),
QT_TRANSLATE_NOOP("bitcoin-core", "Block file load progress "),
QT_TRANSLATE_NOOP("bitcoin-core", "Block not in index"),
QT_TRANSLATE_NOOP("bitcoin-core", "Block read failed"),
QT_TRANSLATE_NOOP("bitcoin-core", "Blocks Loaded"),
QT_TRANSLATE_NOOP("bitcoin-core", "Blocks Verified"),
QT_TRANSLATE_NOOP("bitcoin-core", "Boinc Reward"),
QT_TRANSLATE_NOOP("bitcoin-core", "CPID Count"),
QT_TRANSLATE_NOOP("bitcoin-core", "CPID count polls are not supported."),
QT_TRANSLATE_NOOP("bitcoin-core", "CPID"),
QT_TRANSLATE_NOOP("bitcoin-core", "Cannot resolve -bind address: '%s'"),
QT_TRANSLATE_NOOP("bitcoin-core", "Cannot resolve -externalip address: '%s'"),
QT_TRANSLATE_NOOP("bitcoin-core", "Cannot write default address"),
QT_TRANSLATE_NOOP("bitcoin-core", "Cannot write to data directory '%s'; check permissions."),
QT_TRANSLATE_NOOP("bitcoin-core", "Checking block index..."),
QT_TRANSLATE_NOOP("bitcoin-core", "Client Version"),
QT_TRANSLATE_NOOP("bitcoin-core", "Community"),
QT_TRANSLATE_NOOP("bitcoin-core", "Could not create transaction. See debug.log."),
QT_TRANSLATE_NOOP("bitcoin-core", "Datadir: "),
QT_TRANSLATE_NOOP("bitcoin-core", "Deleted"),
QT_TRANSLATE_NOOP("bitcoin-core", "Difficulty"),
QT_TRANSLATE_NOOP("bitcoin-core", "Directories:"),
QT_TRANSLATE_NOOP("bitcoin-core", "Disabled by configuration"),
QT_TRANSLATE_NOOP("bitcoin-core", "Done loading"),
QT_TRANSLATE_NOOP("bitcoin-core", "Duplicate poll additional field: %s"),
QT_TRANSLATE_NOOP("bitcoin-core", "Duplicate poll choice: %s"),
QT_TRANSLATE_NOOP("bitcoin-core", "Duplicate response for poll choice: %s"),
QT_TRANSLATE_NOOP("bitcoin-core", "ERROR"),
QT_TRANSLATE_NOOP("bitcoin-core", "Eligible for Research Rewards"),
QT_TRANSLATE_NOOP("bitcoin-core", "Entire balance reserved"),
QT_TRANSLATE_NOOP("bitcoin-core", "Error loading %s: Wallet corrupted"),
QT_TRANSLATE_NOOP("bitcoin-core", "Error loading blkindex.dat"),
QT_TRANSLATE_NOOP("bitcoin-core", "Error loading wallet.dat"),
QT_TRANSLATE_NOOP("bitcoin-core", "Error loading wallet.dat: Wallet corrupted"),
QT_TRANSLATE_NOOP("bitcoin-core", "Error loading wallet.dat: Wallet requires newer version of Gridcoin"),
QT_TRANSLATE_NOOP("bitcoin-core", "Error"),
QT_TRANSLATE_NOOP("bitcoin-core", "Error: Transaction creation failed  "),
QT_TRANSLATE_NOOP("bitcoin-core", "Error: Transaction creation failed."),
QT_TRANSLATE_NOOP("bitcoin-core", "Error: Wallet locked, unable to create transaction  "),
QT_TRANSLATE_NOOP("bitcoin-core", "Error: Wallet locked, unable to create transaction."),
QT_TRANSLATE_NOOP("bitcoin-core", "Error: Wallet unlocked for staking only, unable to create transaction."),
QT_TRANSLATE_NOOP("bitcoin-core", "Error: could not start node"),
QT_TRANSLATE_NOOP("bitcoin-core", "Exceeded the number of choices in the poll: %s"),
QT_TRANSLATE_NOOP("bitcoin-core", "Expired while pending"),
QT_TRANSLATE_NOOP("bitcoin-core", "Explorer"),
QT_TRANSLATE_NOOP("bitcoin-core", "Failed to listen on any port. Use -listen=0 if you want this."),
QT_TRANSLATE_NOOP("bitcoin-core", "Failed to rename bootstrap file to .old for backup purposes."),
QT_TRANSLATE_NOOP("bitcoin-core", "Failed: Count = %1"),
QT_TRANSLATE_NOOP("bitcoin-core", "Fees Collected"),
QT_TRANSLATE_NOOP("bitcoin-core", "Files:"),
QT_TRANSLATE_NOOP("bitcoin-core", "For opinion or casual polls without any particular requirements."),
QT_TRANSLATE_NOOP("bitcoin-core", "Get help for a command"),
QT_TRANSLATE_NOOP("bitcoin-core", "GitHub version: "),
QT_TRANSLATE_NOOP("bitcoin-core", "Governance"),
QT_TRANSLATE_NOOP("bitcoin-core", "Gridcoin Update Available"),
QT_TRANSLATE_NOOP("bitcoin-core", "Gridcoin version"),
QT_TRANSLATE_NOOP("bitcoin-core", "Gridcoin"),
QT_TRANSLATE_NOOP("bitcoin-core", "Height"),
QT_TRANSLATE_NOOP("bitcoin-core", "Importing blockchain data file(s)."),
QT_TRANSLATE_NOOP("bitcoin-core", "Importing bootstrap blockchain data file."),
QT_TRANSLATE_NOOP("bitcoin-core", "Inactive"),
QT_TRANSLATE_NOOP("bitcoin-core", "Initialization sanity check failed. Gridcoin is shutting down."),
QT_TRANSLATE_NOOP("bitcoin-core", "Initializing local researcher context..."),
QT_TRANSLATE_NOOP("bitcoin-core", "Initializing registry from stored history for contract type "),
QT_TRANSLATE_NOOP("bitcoin-core", "Initializing research reward accounting..."),
QT_TRANSLATE_NOOP("bitcoin-core", "Insufficient funds"),
QT_TRANSLATE_NOOP("bitcoin-core", "Insufficient funds."),
QT_TRANSLATE_NOOP("bitcoin-core", "Interest"),
QT_TRANSLATE_NOOP("bitcoin-core", "Invalid -proxy address: '%s'"),
QT_TRANSLATE_NOOP("bitcoin-core", "Invalid -tor address: '%s'"),
QT_TRANSLATE_NOOP("bitcoin-core", "Invalid amount for -mininput=<amount>: '%s'"),
QT_TRANSLATE_NOOP("bitcoin-core", "Invalid amount for -paytxfee=<amount>: '%s'"),
QT_TRANSLATE_NOOP("bitcoin-core", "Invalid amount for -peertimeout=<amount>: '%s'"),
QT_TRANSLATE_NOOP("bitcoin-core", "Invalid amount for -reservebalance=<amount>"),
QT_TRANSLATE_NOOP("bitcoin-core", "Invalid amount"),
QT_TRANSLATE_NOOP("bitcoin-core", "Invalid team"),
QT_TRANSLATE_NOOP("bitcoin-core", "Is Superblock"),
QT_TRANSLATE_NOOP("bitcoin-core", "List commands"),
QT_TRANSLATE_NOOP("bitcoin-core", "Loading Network Averages..."),
QT_TRANSLATE_NOOP("bitcoin-core", "Loading addresses..."),
QT_TRANSLATE_NOOP("bitcoin-core", "Loading banlist..."),
QT_TRANSLATE_NOOP("bitcoin-core", "Loading block index..."),
QT_TRANSLATE_NOOP("bitcoin-core", "Loading history for contract type "),
QT_TRANSLATE_NOOP("bitcoin-core", "Loading superblock cache..."),
QT_TRANSLATE_NOOP("bitcoin-core", "Loading wallet..."),
QT_TRANSLATE_NOOP("bitcoin-core", "Local version: "),
QT_TRANSLATE_NOOP("bitcoin-core", "Magnitude"),
QT_TRANSLATE_NOOP("bitcoin-core", "Magnitude+Balance"),
QT_TRANSLATE_NOOP("bitcoin-core", "Magnitude-only polls are not supported."),
QT_TRANSLATE_NOOP("bitcoin-core", "Malformed CPID"),
QT_TRANSLATE_NOOP("bitcoin-core", "Mandatory"),
QT_TRANSLATE_NOOP("bitcoin-core", "Manually Greylisted"),
QT_TRANSLATE_NOOP("bitcoin-core", "Marketing"),
QT_TRANSLATE_NOOP("bitcoin-core", "Multiple Choice"),
QT_TRANSLATE_NOOP("bitcoin-core", "No UTXOs available due to reserve balance"),
QT_TRANSLATE_NOOP("bitcoin-core", "No coins"),
QT_TRANSLATE_NOOP("bitcoin-core", "No current polls"),
QT_TRANSLATE_NOOP("bitcoin-core", "No eligible outputs greater than 1 GRC."),
QT_TRANSLATE_NOOP("bitcoin-core", "No mature coins"),
QT_TRANSLATE_NOOP("bitcoin-core", "No single address has the required %s GRC balance to create a poll."),
QT_TRANSLATE_NOOP("bitcoin-core", "No wallet available."),
QT_TRANSLATE_NOOP("bitcoin-core", "Not authorized"),
QT_TRANSLATE_NOOP("bitcoin-core", "Offline"),
QT_TRANSLATE_NOOP("bitcoin-core", "Organization"),
QT_TRANSLATE_NOOP("bitcoin-core", "Outbound communication to TCP port %1 appears to be blocked. "),
QT_TRANSLATE_NOOP("bitcoin-core", "Outreach"),
QT_TRANSLATE_NOOP("bitcoin-core", "Participant Count"),
QT_TRANSLATE_NOOP("bitcoin-core", "Participant count polls are not supported."),
QT_TRANSLATE_NOOP("bitcoin-core", "Passed: 80 block difficulty is %1."),
QT_TRANSLATE_NOOP("bitcoin-core", "Passed: Count = %1"),
QT_TRANSLATE_NOOP("bitcoin-core", "Passed: ETTS = %1 <= 45 days"),
QT_TRANSLATE_NOOP("bitcoin-core", "Pending"),
QT_TRANSLATE_NOOP("bitcoin-core", "Please enter a poll discussion website URL."),
QT_TRANSLATE_NOOP("bitcoin-core", "Please enter a poll title."),
QT_TRANSLATE_NOOP("bitcoin-core", "Please enter at least one response."),
QT_TRANSLATE_NOOP("bitcoin-core", "Please enter at least two poll choices."),
QT_TRANSLATE_NOOP("bitcoin-core", "Poll additional field name \"%s\" exceeds %s characters."),
QT_TRANSLATE_NOOP("bitcoin-core", "Poll cannot contain more than %s additional fields"),
QT_TRANSLATE_NOOP("bitcoin-core", "Poll cannot contain more than %s choices."),
QT_TRANSLATE_NOOP("bitcoin-core", "Poll choice \"%s\" exceeds %s characters."),
QT_TRANSLATE_NOOP("bitcoin-core", "Poll discussion URL cannot exceed %s characters."),
QT_TRANSLATE_NOOP("bitcoin-core", "Poll duration cannot exceed %s days."),
QT_TRANSLATE_NOOP("bitcoin-core", "Poll duration must be at least %s days."),
QT_TRANSLATE_NOOP("bitcoin-core", "Poll has already finished."),
QT_TRANSLATE_NOOP("bitcoin-core", "Poll only allows a single choice."),
QT_TRANSLATE_NOOP("bitcoin-core", "Poll question cannot exceed %s characters."),
QT_TRANSLATE_NOOP("bitcoin-core", "Poll signature failed. See debug.log."),
QT_TRANSLATE_NOOP("bitcoin-core", "Poll title cannot exceed %s characters."),
QT_TRANSLATE_NOOP("bitcoin-core", "Poll with that title already exists. Please choose another title."),
QT_TRANSLATE_NOOP("bitcoin-core", "Pool"),
QT_TRANSLATE_NOOP("bitcoin-core", "Project Listing"),
QT_TRANSLATE_NOOP("bitcoin-core", "Project email mismatch"),
QT_TRANSLATE_NOOP("bitcoin-core", "Propose a change to Gridcoin at the protocol level."),
QT_TRANSLATE_NOOP("bitcoin-core", "Propose marketing initiatives like ad campaigns."),
QT_TRANSLATE_NOOP("bitcoin-core", "Protocol Development"),
QT_TRANSLATE_NOOP("bitcoin-core", "Quorum Hash"),
QT_TRANSLATE_NOOP("bitcoin-core", "Reindexing blockchain from on disk block data files..."),
QT_TRANSLATE_NOOP("bitcoin-core", "Renewal"),
QT_TRANSLATE_NOOP("bitcoin-core", "Replaying contracts..."),
QT_TRANSLATE_NOOP("bitcoin-core", "Rescanning for MRC requests..."),
QT_TRANSLATE_NOOP("bitcoin-core", "Rescanning..."),
QT_TRANSLATE_NOOP("bitcoin-core", "Reset Blockchain Data: Blockchain data removal failed."),
QT_TRANSLATE_NOOP("bitcoin-core", "Reset Blockchain Data: Blockchain data removal was a success"),
QT_TRANSLATE_NOOP("bitcoin-core", "Resetting block chain index to prepare for reindexing..."),
QT_TRANSLATE_NOOP("bitcoin-core", "Send command to -server or gridcoinresearchd"),
QT_TRANSLATE_NOOP("bitcoin-core", "Single Choice"),
QT_TRANSLATE_NOOP("bitcoin-core", "Staking Only - No Eligible Research Projects"),
QT_TRANSLATE_NOOP("bitcoin-core", "Staking Only - No active beacon"),
QT_TRANSLATE_NOOP("bitcoin-core", "Staking Only - Non-cruncher Mode"),
QT_TRANSLATE_NOOP("bitcoin-core", "Staking Only - Pool Detected"),
QT_TRANSLATE_NOOP("bitcoin-core", "Superblock Binary Size"),
QT_TRANSLATE_NOOP("bitcoin-core", "Survey"),
QT_TRANSLATE_NOOP("bitcoin-core", "Testnet-only version"),
QT_TRANSLATE_NOOP("bitcoin-core", "The field is not well-formed."),
QT_TRANSLATE_NOOP("bitcoin-core", "The field list is not well-formed."),
QT_TRANSLATE_NOOP("bitcoin-core", "The latest release is "),
QT_TRANSLATE_NOOP("bitcoin-core", "This update is "),
QT_TRANSLATE_NOOP("bitcoin-core", "To use the %s option"),
QT_TRANSLATE_NOOP("bitcoin-core", "Unable to bind to %s on this computer (bind returned error %d, %s)"),
QT_TRANSLATE_NOOP("bitcoin-core", "Unable to create the PID file '%s': %s"),
QT_TRANSLATE_NOOP("bitcoin-core", "Unknown error"),
QT_TRANSLATE_NOOP("bitcoin-core", "Unknown network specified in -onlynet: '%s'"),
QT_TRANSLATE_NOOP("bitcoin-core", "Unknown poll response type."),
QT_TRANSLATE_NOOP("bitcoin-core", "Unknown poll type. This should never happen."),
QT_TRANSLATE_NOOP("bitcoin-core", "Unknown poll type."),
QT_TRANSLATE_NOOP("bitcoin-core", "Unknown poll weight type."),
QT_TRANSLATE_NOOP("bitcoin-core", "Unknown"),
QT_TRANSLATE_NOOP("bitcoin-core", "Usage:"),
QT_TRANSLATE_NOOP("bitcoin-core", "Verifying checkpoints..."),
QT_TRANSLATE_NOOP("bitcoin-core", "Verifying database integrity..."),
QT_TRANSLATE_NOOP("bitcoin-core", "Vote signature failed. See debug.log."),
QT_TRANSLATE_NOOP("bitcoin-core", "Wallet %s resides outside data directory %s."),
QT_TRANSLATE_NOOP("bitcoin-core", "Wallet balance of %s in top %s UTXOs is less than required %s GRC."),
QT_TRANSLATE_NOOP("bitcoin-core", "Wallet locked"),
QT_TRANSLATE_NOOP("bitcoin-core", "Wallet needed to be rewritten: restart Gridcoin to complete"),
QT_TRANSLATE_NOOP("bitcoin-core", "Warning: 45 days < ETTS = %1 <= 90 days"),
QT_TRANSLATE_NOOP("bitcoin-core", "Warning: 80 block difficulty is less than %1."),
QT_TRANSLATE_NOOP("bitcoin-core", "Warning: Cannot connect to NTP server"),
QT_TRANSLATE_NOOP("bitcoin-core", "Warning: Count = %1 (Pass = 8+)"),
QT_TRANSLATE_NOOP("bitcoin-core", "Warning: Count = %1"),
QT_TRANSLATE_NOOP("bitcoin-core", "Warning: Disk space is low!"),
QT_TRANSLATE_NOOP("bitcoin-core", "Wrong Payload version specified for current block height."),
QT_TRANSLATE_NOOP("bitcoin-core", "Yes/No/Abstain"),
QT_TRANSLATE_NOOP("bitcoin-core", "You are running the latest release."),
QT_TRANSLATE_NOOP("bitcoin-core", "You should check your time and time zone settings for your computer."),
QT_TRANSLATE_NOOP("bitcoin-core", "You will need to delete the following."),
QT_TRANSLATE_NOOP("bitcoin-core", "\"%s\" is not a valid poll choice."),
QT_TRANSLATE_NOOP("bitcoin-core", "beacon"),
QT_TRANSLATE_NOOP("bitcoin-core", "claim"),
QT_TRANSLATE_NOOP("bitcoin-core", "leisure"),
QT_TRANSLATE_NOOP("bitcoin-core", "mandatory"),
QT_TRANSLATE_NOOP("bitcoin-core", "message"),
QT_TRANSLATE_NOOP("bitcoin-core", "mrc"),
QT_TRANSLATE_NOOP("bitcoin-core", "poll"),
QT_TRANSLATE_NOOP("bitcoin-core", "pool_approve"),
QT_TRANSLATE_NOOP("bitcoin-core", "pool_register"),
QT_TRANSLATE_NOOP("bitcoin-core", "project"),
QT_TRANSLATE_NOOP("bitcoin-core", "protocol"),
QT_TRANSLATE_NOOP("bitcoin-core", "scraper"),
QT_TRANSLATE_NOOP("bitcoin-core", "sidestake"),
QT_TRANSLATE_NOOP("bitcoin-core", "unknown"),
QT_TRANSLATE_NOOP("bitcoin-core", "vote"),
QT_TRANSLATE_NOOP("bitcoin-core", "wallet.dat corrupt, salvage failed"),
};
