.\" Manpage for gridcoinresearchd.
.\" Contact richard.leckinger@riseup.net to correct errors or typos.
.TH man 1 "25 September 2016" "1.0" "gridcoinresearchd man page"
.SH NAME
gridcoinresearchd \- command line gridcoin wallet
.SH SYNOPSIS
gridcoinresearchd
.SH DESCRIPTION
Gridcoin is a peer-to-peer cryptocurrency that uses distributed computing 
(BOINC) to benefit humanity by advancing the progress of medicine, biology, 
climatology, mathematics, astrophysics, and more.

The aim of the Gridcoin project is to shift the computational power primarily 
to BOINC projects whilst the POW mining calculations become a second priority 
- so as the mining network scales up, the network's BOINC contribution is 
scaled up in tandem.
.SH OPTIONS
The gridcoinresearchd is usually started without any options
.SH SEE ALSO
gridcoinresearch(1)
.SH BUGS
No known bugs.
.SH AUTHOR
Richard Leckinger <richard.leckinger@riseup.net>
