#!/usr/bin/env python3
# Copyright (c) 2026 The Gridcoin developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or https://opensource.org/licenses/mit-license.php.

"""IPC method dispatch lint (multiprocess design section 4.4/4.5).

Every interface method in src/ipc/capnp/*.capnp must declare
`context :Proxy.Context`. That parameter is not decoration -- it decides which
THREAD the method body runs on:

  * WITH context, libmultiprocess dispatches the call to a dedicated server
    worker thread (one per client thread per connection).
  * WITHOUT it, the method body runs INLINE ON THE EVENT-LOOP THREAD. A single
    lock acquisition there -- cs_main, cs_wallet, any registry lock -- stalls the
    entire IPC channel for as long as that lock is contended, because the loop
    thread is what services every other call and notification on the connection.

Nothing in the schema language or the generated code warns about this. The
omission compiles, works in every quick test, and only shows up as an
unexplained whole-channel stall under load. So it is checked here.

EXEMPT lists the methods that are legitimately context-free, with the reason.

If you are here because the lint failed, the fix is to add
`context :Proxy.Context` as the first parameter of the flagged method, matching
its neighbours in the same file.
"""

import glob
import os
import re
import sys

CAPNP_GLOB = "src/ipc/capnp/*.capnp"

# "name @N (" at the start of a line -- a method or a struct field. Methods are
# distinguished below by having a parameter list that we then check.
MEMBER_RE = re.compile(r"^\s*([a-zA-Z][a-zA-Z0-9_]*)\s*@(\d+)\s*\(")
# Only interface bodies contain methods; struct bodies contain fields, which
# never take a context. Track which kind of scope we are in.
SCOPE_RE = re.compile(r"^\s*(interface|struct)\s+(\w+)")

# (file basename, method name) -> reason it needs no context.
EXEMPT = {
    ("init.capnp", "construct"):
        "generated by libmultiprocess itself (Proxy.ThreadMap bootstrap); it has no "
        "C++ counterpart on interfaces::Init and must run before any worker thread "
        "exists. Its pre-auth reachability is bounded instead -- see "
        "mp::MAX_SERVER_THREADS_PER_CONNECTION and ipc::IPC_AUTH_DEADLINE.",
}


def fail(msg):
    print("lint-capnp-context: {}".format(msg), file=sys.stderr)


def scope_kind_at(lines, index):
    """The nearest enclosing 'interface' or 'struct' above `index`, by indentation."""
    member_indent = len(lines[index]) - len(lines[index].lstrip())
    for i in range(index - 1, -1, -1):
        m = SCOPE_RE.match(lines[i])
        if not m:
            continue
        scope_indent = len(lines[i]) - len(lines[i].lstrip())
        if scope_indent < member_indent:
            return m.group(1)
    return None


def main():
    files = sorted(glob.glob(CAPNP_GLOB))
    if not files:
        fail("no schemas matched {} -- run from the repository root".format(CAPNP_GLOB))
        return 1

    errors = []
    checked = 0

    for path in files:
        base = os.path.basename(path)
        try:
            with open(path, "r", encoding="utf-8") as f:
                lines = f.read().splitlines()
        except OSError as e:
            fail("could not read {}: {}".format(path, e))
            return 1

        for i, line in enumerate(lines):
            m = MEMBER_RE.match(line)
            if not m:
                continue
            if scope_kind_at(lines, i) != "interface":
                continue  # a struct field, not a method

            name = m.group(1)
            checked += 1
            if "context :Proxy.Context" in line or "context:Proxy.Context" in line:
                continue
            if (base, name) in EXEMPT:
                continue
            errors.append(
                "{}:{}: interface method '{}' does not declare 'context :Proxy.Context', so its "
                "body runs inline on the IPC event-loop thread. One contended lock there stalls "
                "the whole channel. Add the parameter, or add an entry to EXEMPT in this lint "
                "with the reason.".format(path, i + 1, name))

    if not checked:
        fail("parsed no interface methods; the parser is probably broken")
        return 1

    if errors:
        for e in errors:
            fail(e)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
