#!/usr/bin/env python3
# Copyright (c) 2026 The Gridcoin developers
# Distributed under the MIT software license, see the accompanying
# file COPYING or https://opensource.org/licenses/mit-license.php.

"""IPC method dispatch lint (multiprocess design section 4.4/4.5).

Every interface method in src/ipc/capnp/*.capnp must declare
`context :Proxy.Context`. That parameter is not decoration -- it decides which
THREAD the method body runs on:

  * WITH context, libmultiprocess dispatches the call to a dedicated server
    worker thread (one per client thread per connection).
  * WITHOUT it, the method body runs INLINE ON THE EVENT-LOOP THREAD. A single
    lock acquisition there -- cs_main, cs_wallet, any registry lock -- stalls the
    entire IPC channel for as long as that lock is contended, because the loop
    thread is what services every other call and notification on the connection.

Nothing in the schema language or the generated code warns about this. The
omission compiles, works in every quick test, and only shows up as an
unexplained whole-channel stall under load. So it is checked here.

EXEMPT lists the methods that are legitimately context-free, with the reason.

If you are here because the lint failed, the fix is to add
`context :Proxy.Context` as the first parameter of the flagged method, matching
its neighbours in the same file.
"""

import glob
import os
import re
import sys

CAPNP_GLOB = "src/ipc/capnp/*.capnp"

# A member with an ordinal. Whitespace-tolerant across newlines, so a declaration
# split as "makeWallet @7\n    (context :Proxy.Context) -> (...)" is still seen --
# the previous line-anchored form skipped those entirely, which is a fail-open.
MEMBER_RE = re.compile(r"(?<![\w.])([a-zA-Z][a-zA-Z0-9_]*)\s*@(\d+)\s*\(", re.MULTILINE)
# Scope openers, matched on brace structure rather than indentation. Indentation
# was unreliable: a method at column 0 inside an interface resolved to "no
# enclosing scope" and was silently skipped.
SCOPE_RE = re.compile(r"\b(interface|struct|enum|union)\s+(\w+)[^{]*\{")
COMMENT_RE = re.compile(r"#[^\n]*")


def strip_comments(text):
    """Blank out # comments, preserving offsets so positions stay meaningful."""
    return COMMENT_RE.sub(lambda m: " " * len(m.group(0)), text)


def scope_spans(text):
    """[(kind, start_of_body, end_of_body)] for every interface/struct/enum/union."""
    spans = []
    for m in SCOPE_RE.finditer(text):
        start = m.end()
        depth = 1
        i = start
        while i < len(text) and depth:
            if text[i] == "{":
                depth += 1
            elif text[i] == "}":
                depth -= 1
            i += 1
        if depth == 0:
            spans.append((m.group(1), start, i - 1))
    return spans


def innermost_kind(spans, pos):
    """The kind of the tightest scope containing `pos`, or None."""
    best = None
    best_start = -1
    for kind, start, end in spans:
        if start <= pos < end and start > best_start:
            best, best_start = kind, start
    return best


# (file basename, method name) -> reason it needs no context.
CONTEXT_PARAM_RE = re.compile(r"(?<![A-Za-z0-9_])context\s*:\s*Proxy\.Context(?![A-Za-z0-9_])")

EXEMPT = {
    ("init.capnp", "construct"):
        "generated by libmultiprocess itself (Proxy.ThreadMap bootstrap); it has no "
        "C++ counterpart on interfaces::Init and must run before any worker thread "
        "exists. Its pre-auth reachability is bounded instead -- see "
        "mp::MAX_SERVER_THREADS_PER_CONNECTION and ipc::IPC_AUTH_DEADLINE.",
}


def fail(msg):
    print("lint-capnp-context: {}".format(msg), file=sys.stderr)


def main():
    files = sorted(glob.glob(CAPNP_GLOB))
    if not files:
        fail("no schemas matched {} -- run from the repository root".format(CAPNP_GLOB))
        return 1

    errors = []
    checked = 0

    for path in files:
        base = os.path.basename(path)
        try:
            with open(path, "r", encoding="utf-8") as f:
                raw = f.read()
        except OSError as e:
            fail("could not read {}: {}".format(path, e))
            return 1

        text = strip_comments(raw)
        spans = scope_spans(text)

        for m in MEMBER_RE.finditer(text):
            if innermost_kind(spans, m.start()) != "interface":
                continue  # a struct field / enumerant, not a method

            name = m.group(1)
            checked += 1
            # Look at the parameter list itself, wherever it wraps to.
            depth = 1
            j = m.end()
            while j < len(text) and depth:
                if text[j] == "(":
                    depth += 1
                elif text[j] == ")":
                    depth -= 1
                j += 1
            params = " ".join(text[m.end():j - 1].split())
            # Whole-identifier match. A substring test also accepted a field named
            # e.g. `notcontext :Proxy.Context`, so a method could still run inline
            # while this lint reported success -- the fail-open shape this check
            # exists to prevent.
            if CONTEXT_PARAM_RE.search(params):
                continue
            if (base, name) in EXEMPT:
                continue
            line_no = text.count("\n", 0, m.start()) + 1
            errors.append(
                "{}:{}: interface method '{}' does not declare 'context :Proxy.Context', so its "
                "body runs inline on the IPC event-loop thread. One contended lock there stalls "
                "the whole channel. Add the parameter, or add an entry to EXEMPT in this lint "
                "with the reason.".format(path, line_no, name))

    if not checked:
        fail("parsed no interface methods; the parser is probably broken")
        return 1

    if errors:
        for e in errors:
            fail(e)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
