// This is a generated source file for Chilkat version 9.5.0.40
#ifndef _C_CkSshTunnelWH
#define _C_CkSshTunnelWH
#include "chilkatDefs.h"

#include "Chilkat_C.h"

CK_VISIBLE_PUBLIC HCkSshTunnelW CkSshTunnelW_Create(void);
CK_VISIBLE_PUBLIC void CkSshTunnelW_Dispose(HCkSshTunnelW handle);
CK_VISIBLE_PUBLIC void CkSshTunnelW_getAcceptThreadSessionLogPath(HCkSshTunnelW cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putAcceptThreadSessionLogPath(HCkSshTunnelW cHandle, const wchar_t *newVal);
CK_VISIBLE_PUBLIC const wchar_t *CkSshTunnelW_acceptThreadSessionLogPath(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC void CkSshTunnelW_getConnectLog(HCkSshTunnelW cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putConnectLog(HCkSshTunnelW cHandle, const wchar_t *newVal);
CK_VISIBLE_PUBLIC const wchar_t *CkSshTunnelW_connectLog(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC int CkSshTunnelW_getConnectTimeoutMs(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putConnectTimeoutMs(HCkSshTunnelW cHandle, int newVal);
CK_VISIBLE_PUBLIC void CkSshTunnelW_getDebugLogFilePath(HCkSshTunnelW cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putDebugLogFilePath(HCkSshTunnelW cHandle, const wchar_t *newVal);
CK_VISIBLE_PUBLIC const wchar_t *CkSshTunnelW_debugLogFilePath(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC void CkSshTunnelW_getDestHostname(HCkSshTunnelW cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putDestHostname(HCkSshTunnelW cHandle, const wchar_t *newVal);
CK_VISIBLE_PUBLIC const wchar_t *CkSshTunnelW_destHostname(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC int CkSshTunnelW_getDestPort(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putDestPort(HCkSshTunnelW cHandle, int newVal);
CK_VISIBLE_PUBLIC void CkSshTunnelW_getHttpProxyAuthMethod(HCkSshTunnelW cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putHttpProxyAuthMethod(HCkSshTunnelW cHandle, const wchar_t *newVal);
CK_VISIBLE_PUBLIC const wchar_t *CkSshTunnelW_httpProxyAuthMethod(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC void CkSshTunnelW_getHttpProxyDomain(HCkSshTunnelW cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putHttpProxyDomain(HCkSshTunnelW cHandle, const wchar_t *newVal);
CK_VISIBLE_PUBLIC const wchar_t *CkSshTunnelW_httpProxyDomain(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC void CkSshTunnelW_getHttpProxyHostname(HCkSshTunnelW cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putHttpProxyHostname(HCkSshTunnelW cHandle, const wchar_t *newVal);
CK_VISIBLE_PUBLIC const wchar_t *CkSshTunnelW_httpProxyHostname(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC void CkSshTunnelW_getHttpProxyPassword(HCkSshTunnelW cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putHttpProxyPassword(HCkSshTunnelW cHandle, const wchar_t *newVal);
CK_VISIBLE_PUBLIC const wchar_t *CkSshTunnelW_httpProxyPassword(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC int CkSshTunnelW_getHttpProxyPort(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putHttpProxyPort(HCkSshTunnelW cHandle, int newVal);
CK_VISIBLE_PUBLIC void CkSshTunnelW_getHttpProxyUsername(HCkSshTunnelW cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putHttpProxyUsername(HCkSshTunnelW cHandle, const wchar_t *newVal);
CK_VISIBLE_PUBLIC const wchar_t *CkSshTunnelW_httpProxyUsername(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC int CkSshTunnelW_getIdleTimeoutMs(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putIdleTimeoutMs(HCkSshTunnelW cHandle, int newVal);
CK_VISIBLE_PUBLIC BOOL CkSshTunnelW_getIsAccepting(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC BOOL CkSshTunnelW_getKeepConnectLog(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putKeepConnectLog(HCkSshTunnelW cHandle, BOOL newVal);
CK_VISIBLE_PUBLIC void CkSshTunnelW_getLastErrorHtml(HCkSshTunnelW cHandle, HCkString retval);
CK_VISIBLE_PUBLIC const wchar_t *CkSshTunnelW_lastErrorHtml(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC void CkSshTunnelW_getLastErrorText(HCkSshTunnelW cHandle, HCkString retval);
CK_VISIBLE_PUBLIC const wchar_t *CkSshTunnelW_lastErrorText(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC void CkSshTunnelW_getLastErrorXml(HCkSshTunnelW cHandle, HCkString retval);
CK_VISIBLE_PUBLIC const wchar_t *CkSshTunnelW_lastErrorXml(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC void CkSshTunnelW_getListenBindIpAddress(HCkSshTunnelW cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putListenBindIpAddress(HCkSshTunnelW cHandle, const wchar_t *newVal);
CK_VISIBLE_PUBLIC const wchar_t *CkSshTunnelW_listenBindIpAddress(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC int CkSshTunnelW_getListenPort(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC int CkSshTunnelW_getMaxPacketSize(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putMaxPacketSize(HCkSshTunnelW cHandle, int newVal);
CK_VISIBLE_PUBLIC void CkSshTunnelW_getOutboundBindIpAddress(HCkSshTunnelW cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putOutboundBindIpAddress(HCkSshTunnelW cHandle, const wchar_t *newVal);
CK_VISIBLE_PUBLIC const wchar_t *CkSshTunnelW_outboundBindIpAddress(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC int CkSshTunnelW_getOutboundBindPort(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putOutboundBindPort(HCkSshTunnelW cHandle, int newVal);
CK_VISIBLE_PUBLIC int CkSshTunnelW_getSoRcvBuf(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putSoRcvBuf(HCkSshTunnelW cHandle, int newVal);
CK_VISIBLE_PUBLIC int CkSshTunnelW_getSoSndBuf(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putSoSndBuf(HCkSshTunnelW cHandle, int newVal);
CK_VISIBLE_PUBLIC void CkSshTunnelW_getSocksHostname(HCkSshTunnelW cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putSocksHostname(HCkSshTunnelW cHandle, const wchar_t *newVal);
CK_VISIBLE_PUBLIC const wchar_t *CkSshTunnelW_socksHostname(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC void CkSshTunnelW_getSocksPassword(HCkSshTunnelW cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putSocksPassword(HCkSshTunnelW cHandle, const wchar_t *newVal);
CK_VISIBLE_PUBLIC const wchar_t *CkSshTunnelW_socksPassword(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC int CkSshTunnelW_getSocksPort(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putSocksPort(HCkSshTunnelW cHandle, int newVal);
CK_VISIBLE_PUBLIC void CkSshTunnelW_getSocksUsername(HCkSshTunnelW cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putSocksUsername(HCkSshTunnelW cHandle, const wchar_t *newVal);
CK_VISIBLE_PUBLIC const wchar_t *CkSshTunnelW_socksUsername(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC int CkSshTunnelW_getSocksVersion(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putSocksVersion(HCkSshTunnelW cHandle, int newVal);
CK_VISIBLE_PUBLIC void CkSshTunnelW_getSshHostname(HCkSshTunnelW cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putSshHostname(HCkSshTunnelW cHandle, const wchar_t *newVal);
CK_VISIBLE_PUBLIC const wchar_t *CkSshTunnelW_sshHostname(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC void CkSshTunnelW_getSshLogin(HCkSshTunnelW cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putSshLogin(HCkSshTunnelW cHandle, const wchar_t *newVal);
CK_VISIBLE_PUBLIC const wchar_t *CkSshTunnelW_sshLogin(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC void CkSshTunnelW_getSshPassword(HCkSshTunnelW cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putSshPassword(HCkSshTunnelW cHandle, const wchar_t *newVal);
CK_VISIBLE_PUBLIC const wchar_t *CkSshTunnelW_sshPassword(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC int CkSshTunnelW_getSshPort(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putSshPort(HCkSshTunnelW cHandle, int newVal);
CK_VISIBLE_PUBLIC BOOL CkSshTunnelW_getTcpNoDelay(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putTcpNoDelay(HCkSshTunnelW cHandle, BOOL newVal);
CK_VISIBLE_PUBLIC void CkSshTunnelW_getTunnelErrors(HCkSshTunnelW cHandle, HCkString retval);
CK_VISIBLE_PUBLIC const wchar_t *CkSshTunnelW_tunnelErrors(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC void CkSshTunnelW_getTunnelThreadSessionLogPath(HCkSshTunnelW cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putTunnelThreadSessionLogPath(HCkSshTunnelW cHandle, const wchar_t *newVal);
CK_VISIBLE_PUBLIC const wchar_t *CkSshTunnelW_tunnelThreadSessionLogPath(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC BOOL CkSshTunnelW_getVerboseLogging(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC void CkSshTunnelW_putVerboseLogging(HCkSshTunnelW cHandle, BOOL newVal);
CK_VISIBLE_PUBLIC void CkSshTunnelW_getVersion(HCkSshTunnelW cHandle, HCkString retval);
CK_VISIBLE_PUBLIC const wchar_t *CkSshTunnelW_version(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC BOOL CkSshTunnelW_BeginAccepting(HCkSshTunnelW cHandle, int listenPort);
CK_VISIBLE_PUBLIC void CkSshTunnelW_ClearTunnelErrors(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC BOOL CkSshTunnelW_GetTunnelsXml(HCkSshTunnelW cHandle, HCkString outStr);
CK_VISIBLE_PUBLIC const wchar_t *CkSshTunnelW_getTunnelsXml(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC BOOL CkSshTunnelW_SaveLastError(HCkSshTunnelW cHandle, const wchar_t *path);
CK_VISIBLE_PUBLIC BOOL CkSshTunnelW_SetSshAuthenticationKey(HCkSshTunnelW cHandle, HCkSshKeyW key);
CK_VISIBLE_PUBLIC BOOL CkSshTunnelW_StopAccepting(HCkSshTunnelW cHandle);
CK_VISIBLE_PUBLIC BOOL CkSshTunnelW_StopAllTunnels(HCkSshTunnelW cHandle, int maxWaitMs);
CK_VISIBLE_PUBLIC BOOL CkSshTunnelW_UnlockComponent(HCkSshTunnelW cHandle, const wchar_t *unlockCode);
#endif
