// This is a generated source file for Chilkat version 9.5.0.40
#ifndef _C_CkMailMan_H
#define _C_CkMailMan_H
#include "chilkatDefs.h"

#include "Chilkat_C.h"

CK_VISIBLE_PUBLIC HCkMailMan CkMailMan_Create(void);
CK_VISIBLE_PUBLIC void CkMailMan_Dispose(HCkMailMan handle);
CK_VISIBLE_PUBLIC BOOL CkMailMan_getAllOrNone(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putAllOrNone(HCkMailMan cHandle, BOOL newVal);
CK_VISIBLE_PUBLIC BOOL CkMailMan_getAutoFix(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putAutoFix(HCkMailMan cHandle, BOOL newVal);
CK_VISIBLE_PUBLIC BOOL CkMailMan_getAutoGenMessageId(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putAutoGenMessageId(HCkMailMan cHandle, BOOL newVal);
CK_VISIBLE_PUBLIC BOOL CkMailMan_getAutoSmtpRset(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putAutoSmtpRset(HCkMailMan cHandle, BOOL newVal);
CK_VISIBLE_PUBLIC void CkMailMan_getClientIpAddress(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkMailMan_putClientIpAddress(HCkMailMan cHandle, const char *newVal);
CK_VISIBLE_PUBLIC const char *CkMailMan_clientIpAddress(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC int CkMailMan_getConnectTimeout(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putConnectTimeout(HCkMailMan cHandle, int newVal);
CK_VISIBLE_PUBLIC void CkMailMan_getDebugLogFilePath(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkMailMan_putDebugLogFilePath(HCkMailMan cHandle, const char *newVal);
CK_VISIBLE_PUBLIC const char *CkMailMan_debugLogFilePath(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_getDsnEnvid(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkMailMan_putDsnEnvid(HCkMailMan cHandle, const char *newVal);
CK_VISIBLE_PUBLIC const char *CkMailMan_dsnEnvid(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_getDsnNotify(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkMailMan_putDsnNotify(HCkMailMan cHandle, const char *newVal);
CK_VISIBLE_PUBLIC const char *CkMailMan_dsnNotify(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_getDsnRet(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkMailMan_putDsnRet(HCkMailMan cHandle, const char *newVal);
CK_VISIBLE_PUBLIC const char *CkMailMan_dsnRet(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC BOOL CkMailMan_getEmbedCertChain(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putEmbedCertChain(HCkMailMan cHandle, BOOL newVal);
CK_VISIBLE_PUBLIC void CkMailMan_getFilter(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkMailMan_putFilter(HCkMailMan cHandle, const char *newVal);
CK_VISIBLE_PUBLIC const char *CkMailMan_filter(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC int CkMailMan_getHeartbeatMs(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putHeartbeatMs(HCkMailMan cHandle, int newVal);
CK_VISIBLE_PUBLIC void CkMailMan_getHeloHostname(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkMailMan_putHeloHostname(HCkMailMan cHandle, const char *newVal);
CK_VISIBLE_PUBLIC const char *CkMailMan_heloHostname(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_getHttpProxyAuthMethod(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkMailMan_putHttpProxyAuthMethod(HCkMailMan cHandle, const char *newVal);
CK_VISIBLE_PUBLIC const char *CkMailMan_httpProxyAuthMethod(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_getHttpProxyDomain(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkMailMan_putHttpProxyDomain(HCkMailMan cHandle, const char *newVal);
CK_VISIBLE_PUBLIC const char *CkMailMan_httpProxyDomain(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_getHttpProxyHostname(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkMailMan_putHttpProxyHostname(HCkMailMan cHandle, const char *newVal);
CK_VISIBLE_PUBLIC const char *CkMailMan_httpProxyHostname(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_getHttpProxyPassword(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkMailMan_putHttpProxyPassword(HCkMailMan cHandle, const char *newVal);
CK_VISIBLE_PUBLIC const char *CkMailMan_httpProxyPassword(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC int CkMailMan_getHttpProxyPort(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putHttpProxyPort(HCkMailMan cHandle, int newVal);
CK_VISIBLE_PUBLIC void CkMailMan_getHttpProxyUsername(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkMailMan_putHttpProxyUsername(HCkMailMan cHandle, const char *newVal);
CK_VISIBLE_PUBLIC const char *CkMailMan_httpProxyUsername(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC BOOL CkMailMan_getImmediateDelete(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putImmediateDelete(HCkMailMan cHandle, BOOL newVal);
CK_VISIBLE_PUBLIC BOOL CkMailMan_getIncludeRootCert(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putIncludeRootCert(HCkMailMan cHandle, BOOL newVal);
CK_VISIBLE_PUBLIC BOOL CkMailMan_getIsSmtpConnected(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_getLastErrorHtml(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC const char *CkMailMan_lastErrorHtml(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_getLastErrorText(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC const char *CkMailMan_lastErrorText(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_getLastErrorXml(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC const char *CkMailMan_lastErrorXml(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_getLastSendQFilename(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC const char *CkMailMan_lastSendQFilename(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC int CkMailMan_getLastSmtpStatus(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_getLogMailReceivedFilename(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkMailMan_putLogMailReceivedFilename(HCkMailMan cHandle, const char *newVal);
CK_VISIBLE_PUBLIC const char *CkMailMan_logMailReceivedFilename(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_getLogMailSentFilename(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkMailMan_putLogMailSentFilename(HCkMailMan cHandle, const char *newVal);
CK_VISIBLE_PUBLIC const char *CkMailMan_logMailSentFilename(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_getMailHost(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkMailMan_putMailHost(HCkMailMan cHandle, const char *newVal);
CK_VISIBLE_PUBLIC const char *CkMailMan_mailHost(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC int CkMailMan_getMailPort(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putMailPort(HCkMailMan cHandle, int newVal);
CK_VISIBLE_PUBLIC int CkMailMan_getMaxCount(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putMaxCount(HCkMailMan cHandle, int newVal);
CK_VISIBLE_PUBLIC BOOL CkMailMan_getOpaqueSigning(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putOpaqueSigning(HCkMailMan cHandle, BOOL newVal);
CK_VISIBLE_PUBLIC void CkMailMan_getP7mEncryptAttachFilename(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkMailMan_putP7mEncryptAttachFilename(HCkMailMan cHandle, const char *newVal);
CK_VISIBLE_PUBLIC const char *CkMailMan_p7mEncryptAttachFilename(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_getP7mSigAttachFilename(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkMailMan_putP7mSigAttachFilename(HCkMailMan cHandle, const char *newVal);
CK_VISIBLE_PUBLIC const char *CkMailMan_p7mSigAttachFilename(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_getP7sSigAttachFilename(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkMailMan_putP7sSigAttachFilename(HCkMailMan cHandle, const char *newVal);
CK_VISIBLE_PUBLIC const char *CkMailMan_p7sSigAttachFilename(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC BOOL CkMailMan_getPop3SPA(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putPop3SPA(HCkMailMan cHandle, BOOL newVal);
CK_VISIBLE_PUBLIC int CkMailMan_getPop3SessionId(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_getPop3SessionLog(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC const char *CkMailMan_pop3SessionLog(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC BOOL CkMailMan_getPop3SslServerCertVerified(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC BOOL CkMailMan_getPop3Stls(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putPop3Stls(HCkMailMan cHandle, BOOL newVal);
CK_VISIBLE_PUBLIC void CkMailMan_getPopPassword(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkMailMan_putPopPassword(HCkMailMan cHandle, const char *newVal);
CK_VISIBLE_PUBLIC const char *CkMailMan_popPassword(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC BOOL CkMailMan_getPopSsl(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putPopSsl(HCkMailMan cHandle, BOOL newVal);
CK_VISIBLE_PUBLIC void CkMailMan_getPopUsername(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkMailMan_putPopUsername(HCkMailMan cHandle, const char *newVal);
CK_VISIBLE_PUBLIC const char *CkMailMan_popUsername(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC BOOL CkMailMan_getPreferIpv6(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putPreferIpv6(HCkMailMan cHandle, BOOL newVal);
CK_VISIBLE_PUBLIC int CkMailMan_getReadTimeout(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putReadTimeout(HCkMailMan cHandle, int newVal);
CK_VISIBLE_PUBLIC BOOL CkMailMan_getRequireSslCertVerify(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putRequireSslCertVerify(HCkMailMan cHandle, BOOL newVal);
CK_VISIBLE_PUBLIC BOOL CkMailMan_getResetDateOnLoad(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putResetDateOnLoad(HCkMailMan cHandle, BOOL newVal);
CK_VISIBLE_PUBLIC int CkMailMan_getSendBufferSize(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putSendBufferSize(HCkMailMan cHandle, int newVal);
CK_VISIBLE_PUBLIC BOOL CkMailMan_getSendIndividual(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putSendIndividual(HCkMailMan cHandle, BOOL newVal);
CK_VISIBLE_PUBLIC int CkMailMan_getSizeLimit(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putSizeLimit(HCkMailMan cHandle, int newVal);
CK_VISIBLE_PUBLIC void CkMailMan_getSmtpAuthMethod(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkMailMan_putSmtpAuthMethod(HCkMailMan cHandle, const char *newVal);
CK_VISIBLE_PUBLIC const char *CkMailMan_smtpAuthMethod(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_getSmtpHost(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkMailMan_putSmtpHost(HCkMailMan cHandle, const char *newVal);
CK_VISIBLE_PUBLIC const char *CkMailMan_smtpHost(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_getSmtpLoginDomain(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkMailMan_putSmtpLoginDomain(HCkMailMan cHandle, const char *newVal);
CK_VISIBLE_PUBLIC const char *CkMailMan_smtpLoginDomain(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_getSmtpPassword(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkMailMan_putSmtpPassword(HCkMailMan cHandle, const char *newVal);
CK_VISIBLE_PUBLIC const char *CkMailMan_smtpPassword(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC int CkMailMan_getSmtpPort(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putSmtpPort(HCkMailMan cHandle, int newVal);
CK_VISIBLE_PUBLIC void CkMailMan_getSmtpSessionLog(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC const char *CkMailMan_smtpSessionLog(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC BOOL CkMailMan_getSmtpSsl(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putSmtpSsl(HCkMailMan cHandle, BOOL newVal);
CK_VISIBLE_PUBLIC BOOL CkMailMan_getSmtpSslServerCertVerified(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_getSmtpUsername(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkMailMan_putSmtpUsername(HCkMailMan cHandle, const char *newVal);
CK_VISIBLE_PUBLIC const char *CkMailMan_smtpUsername(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC int CkMailMan_getSoRcvBuf(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putSoRcvBuf(HCkMailMan cHandle, int newVal);
CK_VISIBLE_PUBLIC int CkMailMan_getSoSndBuf(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putSoSndBuf(HCkMailMan cHandle, int newVal);
CK_VISIBLE_PUBLIC void CkMailMan_getSocksHostname(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkMailMan_putSocksHostname(HCkMailMan cHandle, const char *newVal);
CK_VISIBLE_PUBLIC const char *CkMailMan_socksHostname(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_getSocksPassword(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkMailMan_putSocksPassword(HCkMailMan cHandle, const char *newVal);
CK_VISIBLE_PUBLIC const char *CkMailMan_socksPassword(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC int CkMailMan_getSocksPort(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putSocksPort(HCkMailMan cHandle, int newVal);
CK_VISIBLE_PUBLIC void CkMailMan_getSocksUsername(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC void CkMailMan_putSocksUsername(HCkMailMan cHandle, const char *newVal);
CK_VISIBLE_PUBLIC const char *CkMailMan_socksUsername(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC int CkMailMan_getSocksVersion(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putSocksVersion(HCkMailMan cHandle, int newVal);
CK_VISIBLE_PUBLIC BOOL CkMailMan_getStartTLS(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putStartTLS(HCkMailMan cHandle, BOOL newVal);
CK_VISIBLE_PUBLIC BOOL CkMailMan_getUseApop(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putUseApop(HCkMailMan cHandle, BOOL newVal);
CK_VISIBLE_PUBLIC BOOL CkMailMan_getUtf8(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putUtf8(HCkMailMan cHandle, BOOL newVal);
CK_VISIBLE_PUBLIC BOOL CkMailMan_getVerboseLogging(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_putVerboseLogging(HCkMailMan cHandle, BOOL newVal);
CK_VISIBLE_PUBLIC void CkMailMan_getVersion(HCkMailMan cHandle, HCkString retval);
CK_VISIBLE_PUBLIC const char *CkMailMan_version(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC BOOL CkMailMan_AddPfxSourceData(HCkMailMan cHandle, HCkByteData pfxData, const char *password);
CK_VISIBLE_PUBLIC BOOL CkMailMan_AddPfxSourceFile(HCkMailMan cHandle, const char *pfxFilePath, const char *password);
CK_VISIBLE_PUBLIC int CkMailMan_CheckMail(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_ClearBadEmailAddresses(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_ClearPop3SessionLog(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC void CkMailMan_ClearSmtpSessionLog(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC BOOL CkMailMan_CloseSmtpConnection(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC HCkEmailBundle CkMailMan_CopyMail(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC BOOL CkMailMan_DeleteBundle(HCkMailMan cHandle, HCkEmailBundle emailBundle);
CK_VISIBLE_PUBLIC BOOL CkMailMan_DeleteByMsgnum(HCkMailMan cHandle, int msgnum);
CK_VISIBLE_PUBLIC BOOL CkMailMan_DeleteByUidl(HCkMailMan cHandle, const char *uidl);
CK_VISIBLE_PUBLIC BOOL CkMailMan_DeleteEmail(HCkMailMan cHandle, HCkEmail email);
CK_VISIBLE_PUBLIC BOOL CkMailMan_DeleteMultiple(HCkMailMan cHandle, HCkStringArray uidlArray);
CK_VISIBLE_PUBLIC HCkEmail CkMailMan_FetchByMsgnum(HCkMailMan cHandle, int msgnum);
CK_VISIBLE_PUBLIC HCkEmail CkMailMan_FetchEmail(HCkMailMan cHandle, const char *uidl);
CK_VISIBLE_PUBLIC BOOL CkMailMan_FetchMime(HCkMailMan cHandle, const char *uidl, HCkByteData outData);
CK_VISIBLE_PUBLIC BOOL CkMailMan_FetchMimeByMsgnum(HCkMailMan cHandle, int msgnum, HCkByteData outBytes);
CK_VISIBLE_PUBLIC HCkEmailBundle CkMailMan_FetchMultiple(HCkMailMan cHandle, HCkStringArray uidlArray);
CK_VISIBLE_PUBLIC HCkEmailBundle CkMailMan_FetchMultipleHeaders(HCkMailMan cHandle, HCkStringArray uidlArray, int numBodyLines);
CK_VISIBLE_PUBLIC HCkStringArray CkMailMan_FetchMultipleMime(HCkMailMan cHandle, HCkStringArray uidlArray);
CK_VISIBLE_PUBLIC HCkEmail CkMailMan_FetchSingleHeader(HCkMailMan cHandle, int numBodyLines, int messageNumber);
CK_VISIBLE_PUBLIC HCkEmail CkMailMan_FetchSingleHeaderByUidl(HCkMailMan cHandle, int numBodyLines, const char *uidl);
CK_VISIBLE_PUBLIC HCkEmailBundle CkMailMan_GetAllHeaders(HCkMailMan cHandle, int numBodyLines);
CK_VISIBLE_PUBLIC HCkStringArray CkMailMan_GetBadEmailAddrs(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC HCkEmail CkMailMan_GetFullEmail(HCkMailMan cHandle, HCkEmail email);
CK_VISIBLE_PUBLIC HCkEmailBundle CkMailMan_GetHeaders(HCkMailMan cHandle, int numBodyLines, int fromIndex, int toIndex);
CK_VISIBLE_PUBLIC int CkMailMan_GetMailboxCount(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC BOOL CkMailMan_GetMailboxInfoXml(HCkMailMan cHandle, HCkString outXml);
CK_VISIBLE_PUBLIC const char *CkMailMan_getMailboxInfoXml(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC unsigned long CkMailMan_GetMailboxSize(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC HCkCert CkMailMan_GetPop3SslServerCert(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC HCkStringArray CkMailMan_GetSentToEmailAddrs(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC int CkMailMan_GetSizeByUidl(HCkMailMan cHandle, const char *uidl);
CK_VISIBLE_PUBLIC HCkCert CkMailMan_GetSmtpSslServerCert(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC HCkStringArray CkMailMan_GetUidls(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC BOOL CkMailMan_IsSmtpDsnCapable(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC BOOL CkMailMan_IsUnlocked(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC HCkEmail CkMailMan_LoadEml(HCkMailMan cHandle, const char *emlFilename);
CK_VISIBLE_PUBLIC HCkEmailBundle CkMailMan_LoadMbx(HCkMailMan cHandle, const char *mbxFileName);
CK_VISIBLE_PUBLIC HCkEmail CkMailMan_LoadMime(HCkMailMan cHandle, const char *mimeText);
CK_VISIBLE_PUBLIC HCkEmail CkMailMan_LoadXmlEmail(HCkMailMan cHandle, const char *filename);
CK_VISIBLE_PUBLIC HCkEmail CkMailMan_LoadXmlEmailString(HCkMailMan cHandle, const char *xmlString);
CK_VISIBLE_PUBLIC HCkEmailBundle CkMailMan_LoadXmlFile(HCkMailMan cHandle, const char *filename);
CK_VISIBLE_PUBLIC HCkEmailBundle CkMailMan_LoadXmlString(HCkMailMan cHandle, const char *xmlString);
#if defined(CK_MX_INCLUDED)
CK_VISIBLE_PUBLIC BOOL CkMailMan_MxLookup(HCkMailMan cHandle, const char *emailAddress, HCkString outStrHostname);
#endif
#if defined(CK_MX_INCLUDED)
CK_VISIBLE_PUBLIC const char *CkMailMan_mxLookup(HCkMailMan cHandle, const char *emailAddress);
#endif
#if defined(CK_MX_INCLUDED)
CK_VISIBLE_PUBLIC HCkStringArray CkMailMan_MxLookupAll(HCkMailMan cHandle, const char *emailAddress);
#endif
CK_VISIBLE_PUBLIC BOOL CkMailMan_OpenSmtpConnection(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC BOOL CkMailMan_Pop3BeginSession(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC BOOL CkMailMan_Pop3EndSession(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC BOOL CkMailMan_Pop3EndSessionNoQuit(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC BOOL CkMailMan_Pop3Noop(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC BOOL CkMailMan_Pop3Reset(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC BOOL CkMailMan_Pop3SendRawCommand(HCkMailMan cHandle, const char *command, const char *charset, HCkString outStr);
CK_VISIBLE_PUBLIC const char *CkMailMan_pop3SendRawCommand(HCkMailMan cHandle, const char *command, const char *charset);
CK_VISIBLE_PUBLIC BOOL CkMailMan_QuickSend(HCkMailMan cHandle, const char *fromAddr, const char *toAddr, const char *subject, const char *body, const char *smtpServer);
CK_VISIBLE_PUBLIC BOOL CkMailMan_RenderToMime(HCkMailMan cHandle, HCkEmail email, HCkString outStr);
CK_VISIBLE_PUBLIC const char *CkMailMan_renderToMime(HCkMailMan cHandle, HCkEmail email);
CK_VISIBLE_PUBLIC BOOL CkMailMan_RenderToMimeBytes(HCkMailMan cHandle, HCkEmail email, HCkByteData outBytes);
CK_VISIBLE_PUBLIC BOOL CkMailMan_SaveLastError(HCkMailMan cHandle, const char *path);
CK_VISIBLE_PUBLIC BOOL CkMailMan_SendBundle(HCkMailMan cHandle, HCkEmailBundle bundle);
CK_VISIBLE_PUBLIC BOOL CkMailMan_SendEmail(HCkMailMan cHandle, HCkEmail email);
CK_VISIBLE_PUBLIC BOOL CkMailMan_SendMime(HCkMailMan cHandle, const char *fromAddr, const char *recipients, const char *mimeSource);
CK_VISIBLE_PUBLIC BOOL CkMailMan_SendMimeBytes(HCkMailMan cHandle, const char *fromAddr, const char *recipients, HCkByteData mimeSource);
#if defined(CK_SMTPQ_INCLUDED)
CK_VISIBLE_PUBLIC BOOL CkMailMan_SendMimeBytesQ(HCkMailMan cHandle, const char *from, const char *recipients, HCkByteData mimeData);
#endif
#if defined(CK_SMTPQ_INCLUDED)
CK_VISIBLE_PUBLIC BOOL CkMailMan_SendMimeQ(HCkMailMan cHandle, const char *fromAddr, const char *recipients, const char *mimeSource);
#endif
CK_VISIBLE_PUBLIC BOOL CkMailMan_SendMimeToList(HCkMailMan cHandle, const char *fromAddr, const char *distListFilename, const char *mimeSource);
#if defined(CK_SMTPQ_INCLUDED)
CK_VISIBLE_PUBLIC BOOL CkMailMan_SendQ(HCkMailMan cHandle, HCkEmail email);
#endif
#if defined(CK_SMTPQ_INCLUDED)
CK_VISIBLE_PUBLIC BOOL CkMailMan_SendQ2(HCkMailMan cHandle, HCkEmail email, const char *queueDir);
#endif
CK_VISIBLE_PUBLIC BOOL CkMailMan_SendToDistributionList(HCkMailMan cHandle, HCkEmail emailObj, HCkStringArray recipientList);
#if defined(CK_CSP_INCLUDED)
CK_VISIBLE_PUBLIC BOOL CkMailMan_SetCSP(HCkMailMan cHandle, HCkCsp csp);
#endif
CK_VISIBLE_PUBLIC BOOL CkMailMan_SetDecryptCert(HCkMailMan cHandle, HCkCert cert);
CK_VISIBLE_PUBLIC BOOL CkMailMan_SetDecryptCert2(HCkMailMan cHandle, HCkCert cert, HCkPrivateKey privateKey);
CK_VISIBLE_PUBLIC BOOL CkMailMan_SetSslClientCert(HCkMailMan cHandle, HCkCert cert);
CK_VISIBLE_PUBLIC BOOL CkMailMan_SetSslClientCertPem(HCkMailMan cHandle, const char *pemDataOrFilename, const char *pemPassword);
CK_VISIBLE_PUBLIC BOOL CkMailMan_SetSslClientCertPfx(HCkMailMan cHandle, const char *pfxFilename, const char *pfxPassword);
CK_VISIBLE_PUBLIC BOOL CkMailMan_SmtpNoop(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC BOOL CkMailMan_SmtpReset(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC BOOL CkMailMan_SmtpSendRawCommand(HCkMailMan cHandle, const char *command, const char *charset, BOOL bEncodeBase64, HCkString outStr);
CK_VISIBLE_PUBLIC const char *CkMailMan_smtpSendRawCommand(HCkMailMan cHandle, const char *command, const char *charset, BOOL bEncodeBase64);
CK_VISIBLE_PUBLIC BOOL CkMailMan_SshAuthenticatePk(HCkMailMan cHandle, BOOL bSmtp, const char *sshUsername, HCkSshKey sshPrivateKey);
CK_VISIBLE_PUBLIC BOOL CkMailMan_SshAuthenticatePw(HCkMailMan cHandle, BOOL bSmtp, const char *sshLogin, const char *sshPassword);
CK_VISIBLE_PUBLIC BOOL CkMailMan_SshCloseTunnel(HCkMailMan cHandle, BOOL bSmtp);
CK_VISIBLE_PUBLIC BOOL CkMailMan_SshTunnel(HCkMailMan cHandle, BOOL bSmtp, const char *sshServerHostname, int sshPort);
CK_VISIBLE_PUBLIC HCkEmailBundle CkMailMan_TransferMail(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC HCkStringArray CkMailMan_TransferMultipleMime(HCkMailMan cHandle, HCkStringArray uidlArray);
CK_VISIBLE_PUBLIC BOOL CkMailMan_UnlockComponent(HCkMailMan cHandle, const char *code);
CK_VISIBLE_PUBLIC BOOL CkMailMan_UseCertVault(HCkMailMan cHandle, HCkXmlCertVault vault);
CK_VISIBLE_PUBLIC BOOL CkMailMan_VerifyPopConnection(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC BOOL CkMailMan_VerifyPopLogin(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC BOOL CkMailMan_VerifyRecips(HCkMailMan cHandle, HCkEmail email, HCkStringArray badAddrs);
CK_VISIBLE_PUBLIC BOOL CkMailMan_VerifySmtpConnection(HCkMailMan cHandle);
CK_VISIBLE_PUBLIC BOOL CkMailMan_VerifySmtpLogin(HCkMailMan cHandle);
#endif
