// This is a generated source file for Chilkat version 9.5.0.40
#ifndef _C_CkEmailWH
#define _C_CkEmailWH
#include "chilkatDefs.h"

#include "Chilkat_C.h"

HCkEmailW CkEmailW_Create(void);
void CkEmailW_Dispose(HCkEmailW handle);
void CkEmailW_getBody(HCkEmailW cHandle, HCkString retval);
void CkEmailW_putBody(HCkEmailW cHandle, const wchar_t *newVal);
const wchar_t *CkEmailW_body(HCkEmailW cHandle);
void CkEmailW_getBounceAddress(HCkEmailW cHandle, HCkString retval);
void CkEmailW_putBounceAddress(HCkEmailW cHandle, const wchar_t *newVal);
const wchar_t *CkEmailW_bounceAddress(HCkEmailW cHandle);
void CkEmailW_getCharset(HCkEmailW cHandle, HCkString retval);
void CkEmailW_putCharset(HCkEmailW cHandle, const wchar_t *newVal);
const wchar_t *CkEmailW_charset(HCkEmailW cHandle);
void CkEmailW_getDebugLogFilePath(HCkEmailW cHandle, HCkString retval);
void CkEmailW_putDebugLogFilePath(HCkEmailW cHandle, const wchar_t *newVal);
const wchar_t *CkEmailW_debugLogFilePath(HCkEmailW cHandle);
BOOL CkEmailW_getDecrypted(HCkEmailW cHandle);
void CkEmailW_getEmailDate(HCkEmailW cHandle, SYSTEMTIME *retval);
void CkEmailW_putEmailDate(HCkEmailW cHandle, SYSTEMTIME *newVal);
void CkEmailW_getEmailDateStr(HCkEmailW cHandle, HCkString retval);
void CkEmailW_putEmailDateStr(HCkEmailW cHandle, const wchar_t *newVal);
const wchar_t *CkEmailW_emailDateStr(HCkEmailW cHandle);
void CkEmailW_getEncryptedBy(HCkEmailW cHandle, HCkString retval);
const wchar_t *CkEmailW_encryptedBy(HCkEmailW cHandle);
void CkEmailW_getFileDistList(HCkEmailW cHandle, HCkString retval);
void CkEmailW_putFileDistList(HCkEmailW cHandle, const wchar_t *newVal);
const wchar_t *CkEmailW_fileDistList(HCkEmailW cHandle);
void CkEmailW_getFrom(HCkEmailW cHandle, HCkString retval);
void CkEmailW_putFrom(HCkEmailW cHandle, const wchar_t *newVal);
const wchar_t *CkEmailW_ck_from(HCkEmailW cHandle);
void CkEmailW_getFromAddress(HCkEmailW cHandle, HCkString retval);
void CkEmailW_putFromAddress(HCkEmailW cHandle, const wchar_t *newVal);
const wchar_t *CkEmailW_fromAddress(HCkEmailW cHandle);
void CkEmailW_getFromName(HCkEmailW cHandle, HCkString retval);
void CkEmailW_putFromName(HCkEmailW cHandle, const wchar_t *newVal);
const wchar_t *CkEmailW_fromName(HCkEmailW cHandle);
void CkEmailW_getHeader(HCkEmailW cHandle, HCkString retval);
const wchar_t *CkEmailW_header(HCkEmailW cHandle);
void CkEmailW_getLanguage(HCkEmailW cHandle, HCkString retval);
const wchar_t *CkEmailW_language(HCkEmailW cHandle);
void CkEmailW_getLastErrorHtml(HCkEmailW cHandle, HCkString retval);
const wchar_t *CkEmailW_lastErrorHtml(HCkEmailW cHandle);
void CkEmailW_getLastErrorText(HCkEmailW cHandle, HCkString retval);
const wchar_t *CkEmailW_lastErrorText(HCkEmailW cHandle);
void CkEmailW_getLastErrorXml(HCkEmailW cHandle, HCkString retval);
const wchar_t *CkEmailW_lastErrorXml(HCkEmailW cHandle);
void CkEmailW_getLocalDate(HCkEmailW cHandle, SYSTEMTIME *retval);
void CkEmailW_putLocalDate(HCkEmailW cHandle, SYSTEMTIME *newVal);
void CkEmailW_getLocalDateStr(HCkEmailW cHandle, HCkString retval);
void CkEmailW_putLocalDateStr(HCkEmailW cHandle, const wchar_t *newVal);
const wchar_t *CkEmailW_localDateStr(HCkEmailW cHandle);
void CkEmailW_getMailer(HCkEmailW cHandle, HCkString retval);
void CkEmailW_putMailer(HCkEmailW cHandle, const wchar_t *newVal);
const wchar_t *CkEmailW_mailer(HCkEmailW cHandle);
int CkEmailW_getNumAlternatives(HCkEmailW cHandle);
int CkEmailW_getNumAttachedMessages(HCkEmailW cHandle);
int CkEmailW_getNumAttachments(HCkEmailW cHandle);
int CkEmailW_getNumBcc(HCkEmailW cHandle);
int CkEmailW_getNumCC(HCkEmailW cHandle);
int CkEmailW_getNumDaysOld(HCkEmailW cHandle);
int CkEmailW_getNumHeaderFields(HCkEmailW cHandle);
int CkEmailW_getNumRelatedItems(HCkEmailW cHandle);
int CkEmailW_getNumReplacePatterns(HCkEmailW cHandle);
int CkEmailW_getNumReports(HCkEmailW cHandle);
int CkEmailW_getNumTo(HCkEmailW cHandle);
BOOL CkEmailW_getOverwriteExisting(HCkEmailW cHandle);
void CkEmailW_putOverwriteExisting(HCkEmailW cHandle, BOOL newVal);
void CkEmailW_getPkcs7CryptAlg(HCkEmailW cHandle, HCkString retval);
void CkEmailW_putPkcs7CryptAlg(HCkEmailW cHandle, const wchar_t *newVal);
const wchar_t *CkEmailW_pkcs7CryptAlg(HCkEmailW cHandle);
int CkEmailW_getPkcs7KeyLength(HCkEmailW cHandle);
void CkEmailW_putPkcs7KeyLength(HCkEmailW cHandle, int newVal);
void CkEmailW_getPreferredCharset(HCkEmailW cHandle, HCkString retval);
void CkEmailW_putPreferredCharset(HCkEmailW cHandle, const wchar_t *newVal);
const wchar_t *CkEmailW_preferredCharset(HCkEmailW cHandle);
BOOL CkEmailW_getPrependHeaders(HCkEmailW cHandle);
void CkEmailW_putPrependHeaders(HCkEmailW cHandle, BOOL newVal);
BOOL CkEmailW_getReceivedEncrypted(HCkEmailW cHandle);
BOOL CkEmailW_getReceivedSigned(HCkEmailW cHandle);
void CkEmailW_getReplyTo(HCkEmailW cHandle, HCkString retval);
void CkEmailW_putReplyTo(HCkEmailW cHandle, const wchar_t *newVal);
const wchar_t *CkEmailW_replyTo(HCkEmailW cHandle);
BOOL CkEmailW_getReturnReceipt(HCkEmailW cHandle);
void CkEmailW_putReturnReceipt(HCkEmailW cHandle, BOOL newVal);
BOOL CkEmailW_getSendEncrypted(HCkEmailW cHandle);
void CkEmailW_putSendEncrypted(HCkEmailW cHandle, BOOL newVal);
BOOL CkEmailW_getSendSigned(HCkEmailW cHandle);
void CkEmailW_putSendSigned(HCkEmailW cHandle, BOOL newVal);
void CkEmailW_getSender(HCkEmailW cHandle, HCkString retval);
void CkEmailW_putSender(HCkEmailW cHandle, const wchar_t *newVal);
const wchar_t *CkEmailW_sender(HCkEmailW cHandle);
BOOL CkEmailW_getSignaturesValid(HCkEmailW cHandle);
void CkEmailW_getSignedBy(HCkEmailW cHandle, HCkString retval);
const wchar_t *CkEmailW_signedBy(HCkEmailW cHandle);
void CkEmailW_getSigningHashAlg(HCkEmailW cHandle, HCkString retval);
void CkEmailW_putSigningHashAlg(HCkEmailW cHandle, const wchar_t *newVal);
const wchar_t *CkEmailW_signingHashAlg(HCkEmailW cHandle);
int CkEmailW_getSize(HCkEmailW cHandle);
void CkEmailW_getSubject(HCkEmailW cHandle, HCkString retval);
void CkEmailW_putSubject(HCkEmailW cHandle, const wchar_t *newVal);
const wchar_t *CkEmailW_subject(HCkEmailW cHandle);
void CkEmailW_getUidl(HCkEmailW cHandle, HCkString retval);
const wchar_t *CkEmailW_uidl(HCkEmailW cHandle);
BOOL CkEmailW_getUnpackUseRelPaths(HCkEmailW cHandle);
void CkEmailW_putUnpackUseRelPaths(HCkEmailW cHandle, BOOL newVal);
BOOL CkEmailW_getVerboseLogging(HCkEmailW cHandle);
void CkEmailW_putVerboseLogging(HCkEmailW cHandle, BOOL newVal);
void CkEmailW_getVersion(HCkEmailW cHandle, HCkString retval);
const wchar_t *CkEmailW_version(HCkEmailW cHandle);
void CkEmailW_AddAttachmentHeader(HCkEmailW cHandle, int index, const wchar_t *fieldName, const wchar_t *fieldValue);
BOOL CkEmailW_AddBcc(HCkEmailW cHandle, const wchar_t *friendlyName, const wchar_t *emailAddress);
BOOL CkEmailW_AddCC(HCkEmailW cHandle, const wchar_t *friendlyName, const wchar_t *emailAddress);
BOOL CkEmailW_AddDataAttachment(HCkEmailW cHandle, const wchar_t *filePath, HCkByteData content);
BOOL CkEmailW_AddDataAttachment2(HCkEmailW cHandle, const wchar_t *path, HCkByteData content, const wchar_t *contentType);
BOOL CkEmailW_AddEncryptCert(HCkEmailW cHandle, HCkCertW cert);
BOOL CkEmailW_AddFileAttachment(HCkEmailW cHandle, const wchar_t *path, HCkString outStrContentType);
const wchar_t *CkEmailW_addFileAttachment(HCkEmailW cHandle, const wchar_t *path);
BOOL CkEmailW_AddFileAttachment2(HCkEmailW cHandle, const wchar_t *path, const wchar_t *contentType);
void CkEmailW_AddHeaderField(HCkEmailW cHandle, const wchar_t *fieldName, const wchar_t *fieldValue);
void CkEmailW_AddHeaderField2(HCkEmailW cHandle, const wchar_t *fieldName, const wchar_t *fieldValue);
BOOL CkEmailW_AddHtmlAlternativeBody(HCkEmailW cHandle, const wchar_t *body);
BOOL CkEmailW_AddMultipleBcc(HCkEmailW cHandle, const wchar_t *commaSeparatedAddresses);
BOOL CkEmailW_AddMultipleCC(HCkEmailW cHandle, const wchar_t *commaSeparatedAddresses);
BOOL CkEmailW_AddMultipleTo(HCkEmailW cHandle, const wchar_t *commaSeparatedAddresses);
BOOL CkEmailW_AddPfxSourceData(HCkEmailW cHandle, HCkByteData pfxBytes, const wchar_t *pfxPassword);
BOOL CkEmailW_AddPfxSourceFile(HCkEmailW cHandle, const wchar_t *pfxFilePath, const wchar_t *pfxPassword);
BOOL CkEmailW_AddPlainTextAlternativeBody(HCkEmailW cHandle, const wchar_t *body);
BOOL CkEmailW_AddRelatedData(HCkEmailW cHandle, const wchar_t *path, HCkByteData inData, HCkString outStr);
const wchar_t *CkEmailW_addRelatedData(HCkEmailW cHandle, const wchar_t *path, HCkByteData inData);
void CkEmailW_AddRelatedData2(HCkEmailW cHandle, HCkByteData inData, const wchar_t *fileNameInHtml);
#if !defined(CHILKAT_MONO)
void CkEmailW_AddRelatedData2P(HCkEmailW cHandle, const unsigned char *pBytes, unsigned long szBytes, const wchar_t *fileNameInHtml);
#endif
#if !defined(CHILKAT_MONO)
BOOL CkEmailW_AddRelatedDataP(HCkEmailW cHandle, const wchar_t *nameInHtml, const unsigned char *pBytes, unsigned long szBytes, HCkString outStrContentId);
#endif
#if !defined(CHILKAT_MONO)
const wchar_t *CkEmailW_addRelatedDataP(HCkEmailW cHandle, const wchar_t *nameInHtml, const unsigned char *pBytes, unsigned long szBytes);
#endif
BOOL CkEmailW_AddRelatedFile(HCkEmailW cHandle, const wchar_t *path, HCkString outStrContentID);
const wchar_t *CkEmailW_addRelatedFile(HCkEmailW cHandle, const wchar_t *path);
BOOL CkEmailW_AddRelatedFile2(HCkEmailW cHandle, const wchar_t *filenameOnDisk, const wchar_t *filenameInHtml);
void CkEmailW_AddRelatedHeader(HCkEmailW cHandle, int index, const wchar_t *fieldName, const wchar_t *fieldValue);
BOOL CkEmailW_AddRelatedString(HCkEmailW cHandle, const wchar_t *nameInHtml, const wchar_t *str, const wchar_t *charset, HCkString outCid);
const wchar_t *CkEmailW_addRelatedString(HCkEmailW cHandle, const wchar_t *nameInHtml, const wchar_t *str, const wchar_t *charset);
void CkEmailW_AddRelatedString2(HCkEmailW cHandle, const wchar_t *content, const wchar_t *charset, const wchar_t *fileNameInHtml);
BOOL CkEmailW_AddStringAttachment(HCkEmailW cHandle, const wchar_t *path, const wchar_t *content);
BOOL CkEmailW_AddStringAttachment2(HCkEmailW cHandle, const wchar_t *path, const wchar_t *content, const wchar_t *charset);
BOOL CkEmailW_AddTo(HCkEmailW cHandle, const wchar_t *friendlyName, const wchar_t *emailAddress);
BOOL CkEmailW_AddiCalendarAlternativeBody(HCkEmailW cHandle, const wchar_t *icalContent, const wchar_t *methodName);
BOOL CkEmailW_AesDecrypt(HCkEmailW cHandle, const wchar_t *password);
BOOL CkEmailW_AesEncrypt(HCkEmailW cHandle, const wchar_t *password);
void CkEmailW_AppendToBody(HCkEmailW cHandle, const wchar_t *str);
BOOL CkEmailW_AspUnpack(HCkEmailW cHandle, const wchar_t *prefix, const wchar_t *saveDir, const wchar_t *urlPath, BOOL cleanFiles);
BOOL CkEmailW_AspUnpack2(HCkEmailW cHandle, const wchar_t *prefix, const wchar_t *saveDir, const wchar_t *urlPath, BOOL cleanFiles, HCkByteData outHtml);
BOOL CkEmailW_AttachMessage(HCkEmailW cHandle, HCkByteData mimeBytes);
BOOL CkEmailW_BEncodeBytes(HCkEmailW cHandle, HCkByteData inData, const wchar_t *charset, HCkString outEncodedStr);
const wchar_t *CkEmailW_bEncodeBytes(HCkEmailW cHandle, HCkByteData inData, const wchar_t *charset);
BOOL CkEmailW_BEncodeString(HCkEmailW cHandle, const wchar_t *str, const wchar_t *charset, HCkString outEncodedStr);
const wchar_t *CkEmailW_bEncodeString(HCkEmailW cHandle, const wchar_t *str, const wchar_t *charset);
void CkEmailW_ClearBcc(HCkEmailW cHandle);
void CkEmailW_ClearCC(HCkEmailW cHandle);
void CkEmailW_ClearEncryptCerts(HCkEmailW cHandle);
void CkEmailW_ClearTo(HCkEmailW cHandle);
HCkEmailW CkEmailW_Clone(HCkEmailW cHandle);
BOOL CkEmailW_ComputeGlobalKey(HCkEmailW cHandle, const wchar_t *encoding, BOOL bFold, HCkString outStr);
const wchar_t *CkEmailW_computeGlobalKey(HCkEmailW cHandle, const wchar_t *encoding, BOOL bFold);
HCkEmailW CkEmailW_CreateDsn(HCkEmailW cHandle, const wchar_t *humanReadableMessage, const wchar_t *xmlStatusFields, BOOL bHeaderOnly);
HCkEmailW CkEmailW_CreateForward(HCkEmailW cHandle);
HCkEmailW CkEmailW_CreateMdn(HCkEmailW cHandle, const wchar_t *humanReadableMessage, const wchar_t *xmlStatusFields, BOOL bHeaderOnly);
HCkEmailW CkEmailW_CreateReply(HCkEmailW cHandle);
BOOL CkEmailW_CreateTempMht(HCkEmailW cHandle, const wchar_t *inFilename, HCkString outPath);
const wchar_t *CkEmailW_createTempMht(HCkEmailW cHandle, const wchar_t *inFilename);
void CkEmailW_DropAttachments(HCkEmailW cHandle);
void CkEmailW_DropRelatedItem(HCkEmailW cHandle, int index);
void CkEmailW_DropRelatedItems(HCkEmailW cHandle);
BOOL CkEmailW_DropSingleAttachment(HCkEmailW cHandle, int index);
HCkCertW CkEmailW_FindIssuer(HCkEmailW cHandle, HCkCertW cert);
BOOL CkEmailW_GenerateFilename(HCkEmailW cHandle, HCkString outStrFilename);
const wchar_t *CkEmailW_generateFilename(HCkEmailW cHandle);
BOOL CkEmailW_GetAltHeaderField(HCkEmailW cHandle, int index, const wchar_t *fieldName, HCkString outStr);
const wchar_t *CkEmailW_getAltHeaderField(HCkEmailW cHandle, int index, const wchar_t *fieldName);
BOOL CkEmailW_GetAlternativeBody(HCkEmailW cHandle, int index, HCkString outStrBody);
const wchar_t *CkEmailW_getAlternativeBody(HCkEmailW cHandle, int index);
BOOL CkEmailW_GetAlternativeBodyByContentType(HCkEmailW cHandle, const wchar_t *contentType, HCkString outStr);
const wchar_t *CkEmailW_getAlternativeBodyByContentType(HCkEmailW cHandle, const wchar_t *contentType);
BOOL CkEmailW_GetAlternativeContentType(HCkEmailW cHandle, int index, HCkString outStrContentType);
const wchar_t *CkEmailW_getAlternativeContentType(HCkEmailW cHandle, int index);
HCkEmailW CkEmailW_GetAttachedMessage(HCkEmailW cHandle, int index);
BOOL CkEmailW_GetAttachedMessageAttr(HCkEmailW cHandle, int index, const wchar_t *fieldName, const wchar_t *attrName, HCkString outStr);
const wchar_t *CkEmailW_getAttachedMessageAttr(HCkEmailW cHandle, int index, const wchar_t *fieldName, const wchar_t *attrName);
BOOL CkEmailW_GetAttachedMessageFilename(HCkEmailW cHandle, int index, HCkString outStr);
const wchar_t *CkEmailW_getAttachedMessageFilename(HCkEmailW cHandle, int index);
BOOL CkEmailW_GetAttachmentAttr(HCkEmailW cHandle, int index, const wchar_t *fieldName, const wchar_t *attrName, HCkString outStr);
const wchar_t *CkEmailW_getAttachmentAttr(HCkEmailW cHandle, int index, const wchar_t *fieldName, const wchar_t *attrName);
BOOL CkEmailW_GetAttachmentContentID(HCkEmailW cHandle, int index, HCkString outStrContentID);
const wchar_t *CkEmailW_getAttachmentContentID(HCkEmailW cHandle, int index);
BOOL CkEmailW_GetAttachmentContentType(HCkEmailW cHandle, int index, HCkString outStrContentType);
const wchar_t *CkEmailW_getAttachmentContentType(HCkEmailW cHandle, int index);
BOOL CkEmailW_GetAttachmentData(HCkEmailW cHandle, int index, HCkByteData outData);
BOOL CkEmailW_GetAttachmentFilename(HCkEmailW cHandle, int index, HCkString outStrFilename);
const wchar_t *CkEmailW_getAttachmentFilename(HCkEmailW cHandle, int index);
BOOL CkEmailW_GetAttachmentHeader(HCkEmailW cHandle, int attachIndex, const wchar_t *fieldName, HCkString outFieldValue);
const wchar_t *CkEmailW_getAttachmentHeader(HCkEmailW cHandle, int attachIndex, const wchar_t *fieldName);
int CkEmailW_GetAttachmentSize(HCkEmailW cHandle, int index);
BOOL CkEmailW_GetAttachmentString(HCkEmailW cHandle, int index, const wchar_t *charset, HCkString outStr);
const wchar_t *CkEmailW_getAttachmentString(HCkEmailW cHandle, int index, const wchar_t *charset);
BOOL CkEmailW_GetAttachmentStringCrLf(HCkEmailW cHandle, int index, const wchar_t *charset, HCkString outStrData);
const wchar_t *CkEmailW_getAttachmentStringCrLf(HCkEmailW cHandle, int index, const wchar_t *charset);
BOOL CkEmailW_GetBcc(HCkEmailW cHandle, int index, HCkString outStr);
const wchar_t *CkEmailW_getBcc(HCkEmailW cHandle, int index);
BOOL CkEmailW_GetBccAddr(HCkEmailW cHandle, int index, HCkString outStr);
const wchar_t *CkEmailW_getBccAddr(HCkEmailW cHandle, int index);
BOOL CkEmailW_GetBccName(HCkEmailW cHandle, int index, HCkString outStr);
const wchar_t *CkEmailW_getBccName(HCkEmailW cHandle, int index);
BOOL CkEmailW_GetCC(HCkEmailW cHandle, int index, HCkString outStr);
const wchar_t *CkEmailW_getCC(HCkEmailW cHandle, int index);
BOOL CkEmailW_GetCcAddr(HCkEmailW cHandle, int index, HCkString outStr);
const wchar_t *CkEmailW_getCcAddr(HCkEmailW cHandle, int index);
BOOL CkEmailW_GetCcName(HCkEmailW cHandle, int index, HCkString outStr);
const wchar_t *CkEmailW_getCcName(HCkEmailW cHandle, int index);
BOOL CkEmailW_GetDeliveryStatusInfo(HCkEmailW cHandle, const wchar_t *fieldName, HCkString outFieldValue);
const wchar_t *CkEmailW_getDeliveryStatusInfo(HCkEmailW cHandle, const wchar_t *fieldName);
HCkStringArrayW CkEmailW_GetDsnFinalRecipients(HCkEmailW cHandle);
HCkDateTimeW CkEmailW_GetDt(HCkEmailW cHandle);
HCkCertW CkEmailW_GetEncryptCert(HCkEmailW cHandle);
HCkCertW CkEmailW_GetEncryptedByCert(HCkEmailW cHandle);
BOOL CkEmailW_GetFileContent(HCkEmailW cHandle, const wchar_t *path, HCkByteData outData);
BOOL CkEmailW_GetHeaderField(HCkEmailW cHandle, const wchar_t *fieldName, HCkString outStrFieldData);
const wchar_t *CkEmailW_getHeaderField(HCkEmailW cHandle, const wchar_t *fieldName);
BOOL CkEmailW_GetHeaderFieldName(HCkEmailW cHandle, int index, HCkString outStrFieldName);
const wchar_t *CkEmailW_getHeaderFieldName(HCkEmailW cHandle, int index);
BOOL CkEmailW_GetHeaderFieldValue(HCkEmailW cHandle, int index, HCkString outStrFieldValue);
const wchar_t *CkEmailW_getHeaderFieldValue(HCkEmailW cHandle, int index);
BOOL CkEmailW_GetHtmlBody(HCkEmailW cHandle, HCkString outStrBody);
const wchar_t *CkEmailW_getHtmlBody(HCkEmailW cHandle);
int CkEmailW_GetImapUid(HCkEmailW cHandle);
HCkStringArrayW CkEmailW_GetLinkedDomains(HCkEmailW cHandle);
BOOL CkEmailW_GetMbHeaderField(HCkEmailW cHandle, const wchar_t *fieldName, const wchar_t *charset, HCkByteData outBytes);
BOOL CkEmailW_GetMbHtmlBody(HCkEmailW cHandle, const wchar_t *charset, HCkByteData outData);
BOOL CkEmailW_GetMbPlainTextBody(HCkEmailW cHandle, const wchar_t *charset, HCkByteData outData);
BOOL CkEmailW_GetMime(HCkEmailW cHandle, HCkString outStrMime);
const wchar_t *CkEmailW_getMime(HCkEmailW cHandle);
BOOL CkEmailW_GetMimeBinary(HCkEmailW cHandle, HCkByteData outBytes);
BOOL CkEmailW_GetPlainTextBody(HCkEmailW cHandle, HCkString outStrBody);
const wchar_t *CkEmailW_getPlainTextBody(HCkEmailW cHandle);
BOOL CkEmailW_GetRelatedAttr(HCkEmailW cHandle, int index, const wchar_t *fieldName, const wchar_t *attrName, HCkString outStr);
const wchar_t *CkEmailW_getRelatedAttr(HCkEmailW cHandle, int index, const wchar_t *fieldName, const wchar_t *attrName);
BOOL CkEmailW_GetRelatedContentID(HCkEmailW cHandle, int index, HCkString outStrContentID);
const wchar_t *CkEmailW_getRelatedContentID(HCkEmailW cHandle, int index);
BOOL CkEmailW_GetRelatedContentLocation(HCkEmailW cHandle, int index, HCkString outStr);
const wchar_t *CkEmailW_getRelatedContentLocation(HCkEmailW cHandle, int index);
BOOL CkEmailW_GetRelatedContentType(HCkEmailW cHandle, int index, HCkString outStrContentType);
const wchar_t *CkEmailW_getRelatedContentType(HCkEmailW cHandle, int index);
BOOL CkEmailW_GetRelatedData(HCkEmailW cHandle, int index, HCkByteData outBuffer);
BOOL CkEmailW_GetRelatedFilename(HCkEmailW cHandle, int index, HCkString outStrFilename);
const wchar_t *CkEmailW_getRelatedFilename(HCkEmailW cHandle, int index);
BOOL CkEmailW_GetRelatedString(HCkEmailW cHandle, int index, const wchar_t *charset, HCkString outStrData);
const wchar_t *CkEmailW_getRelatedString(HCkEmailW cHandle, int index, const wchar_t *charset);
BOOL CkEmailW_GetRelatedStringCrLf(HCkEmailW cHandle, int index, const wchar_t *charset, HCkString outStr);
const wchar_t *CkEmailW_getRelatedStringCrLf(HCkEmailW cHandle, int index, const wchar_t *charset);
BOOL CkEmailW_GetReplacePattern(HCkEmailW cHandle, int index, HCkString outStrPattern);
const wchar_t *CkEmailW_getReplacePattern(HCkEmailW cHandle, int index);
BOOL CkEmailW_GetReplaceString(HCkEmailW cHandle, int index, HCkString outStr);
const wchar_t *CkEmailW_getReplaceString(HCkEmailW cHandle, int index);
BOOL CkEmailW_GetReplaceString2(HCkEmailW cHandle, const wchar_t *pattern, HCkString outStr);
const wchar_t *CkEmailW_getReplaceString2(HCkEmailW cHandle, const wchar_t *pattern);
BOOL CkEmailW_GetReport(HCkEmailW cHandle, int index, HCkString outStr);
const wchar_t *CkEmailW_getReport(HCkEmailW cHandle, int index);
HCkCertW CkEmailW_GetSignedByCert(HCkEmailW cHandle);
HCkCertChainW CkEmailW_GetSignedByCertChain(HCkEmailW cHandle);
HCkCertW CkEmailW_GetSigningCert(HCkEmailW cHandle);
BOOL CkEmailW_GetTo(HCkEmailW cHandle, int index, HCkString outStr);
const wchar_t *CkEmailW_getTo(HCkEmailW cHandle, int index);
BOOL CkEmailW_GetToAddr(HCkEmailW cHandle, int index, HCkString outStr);
const wchar_t *CkEmailW_getToAddr(HCkEmailW cHandle, int index);
BOOL CkEmailW_GetToName(HCkEmailW cHandle, int index, HCkString outStr);
const wchar_t *CkEmailW_getToName(HCkEmailW cHandle, int index);
BOOL CkEmailW_GetXml(HCkEmailW cHandle, HCkString outStrXml);
const wchar_t *CkEmailW_getXml(HCkEmailW cHandle);
BOOL CkEmailW_HasHeaderMatching(HCkEmailW cHandle, const wchar_t *fieldName, const wchar_t *valuePattern, BOOL caseSensitive);
BOOL CkEmailW_HasHtmlBody(HCkEmailW cHandle);
BOOL CkEmailW_HasPlainTextBody(HCkEmailW cHandle);
BOOL CkEmailW_IsMultipartReport(HCkEmailW cHandle);
BOOL CkEmailW_LoadEml(HCkEmailW cHandle, const wchar_t *mimePath);
BOOL CkEmailW_LoadXml(HCkEmailW cHandle, const wchar_t *xmlPath);
BOOL CkEmailW_LoadXmlString(HCkEmailW cHandle, const wchar_t *xmlStr);
BOOL CkEmailW_QEncodeBytes(HCkEmailW cHandle, HCkByteData inData, const wchar_t *charset, HCkString outEncodedStr);
const wchar_t *CkEmailW_qEncodeBytes(HCkEmailW cHandle, HCkByteData inData, const wchar_t *charset);
BOOL CkEmailW_QEncodeString(HCkEmailW cHandle, const wchar_t *str, const wchar_t *charset, HCkString outEncodedStr);
const wchar_t *CkEmailW_qEncodeString(HCkEmailW cHandle, const wchar_t *str, const wchar_t *charset);
void CkEmailW_RemoveAttachedMessage(HCkEmailW cHandle, int idx);
void CkEmailW_RemoveAttachedMessages(HCkEmailW cHandle);
void CkEmailW_RemoveAttachmentPaths(HCkEmailW cHandle);
void CkEmailW_RemoveHeaderField(HCkEmailW cHandle, const wchar_t *fieldName);
void CkEmailW_RemoveHtmlAlternative(HCkEmailW cHandle);
void CkEmailW_RemovePlainTextAlternative(HCkEmailW cHandle);
BOOL CkEmailW_SaveAllAttachments(HCkEmailW cHandle, const wchar_t *dirPath);
BOOL CkEmailW_SaveAttachedFile(HCkEmailW cHandle, int index, const wchar_t *dirPath);
BOOL CkEmailW_SaveEml(HCkEmailW cHandle, const wchar_t *emlFilePath);
BOOL CkEmailW_SaveLastError(HCkEmailW cHandle, const wchar_t *path);
BOOL CkEmailW_SaveRelatedItem(HCkEmailW cHandle, int index, const wchar_t *dirPath);
BOOL CkEmailW_SaveXml(HCkEmailW cHandle, const wchar_t *path);
BOOL CkEmailW_SetAttachmentCharset(HCkEmailW cHandle, int index, const wchar_t *charset);
BOOL CkEmailW_SetAttachmentDisposition(HCkEmailW cHandle, int index, const wchar_t *disposition);
BOOL CkEmailW_SetAttachmentFilename(HCkEmailW cHandle, int index, const wchar_t *filename);
#if defined(CK_CSP_INCLUDED)
BOOL CkEmailW_SetCSP(HCkEmailW cHandle, HCkCspW csp);
#endif
BOOL CkEmailW_SetDecryptCert(HCkEmailW cHandle, HCkCertW cert);
BOOL CkEmailW_SetDecryptCert2(HCkEmailW cHandle, HCkCertW cert, HCkPrivateKeyW key);
BOOL CkEmailW_SetDt(HCkEmailW cHandle, HCkDateTimeW dt);
void CkEmailW_SetEdifactBody(HCkEmailW cHandle, const wchar_t *message, const wchar_t *name, const wchar_t *filename, const wchar_t *charset);
BOOL CkEmailW_SetEncryptCert(HCkEmailW cHandle, HCkCertW cert);
BOOL CkEmailW_SetFromMimeBytes(HCkEmailW cHandle, HCkByteData mimeBytes);
BOOL CkEmailW_SetFromMimeBytes2(HCkEmailW cHandle, HCkByteData mimeBytes, const wchar_t *charset);
BOOL CkEmailW_SetFromMimeText(HCkEmailW cHandle, const wchar_t *mimeText);
BOOL CkEmailW_SetFromXmlText(HCkEmailW cHandle, const wchar_t *xmlStr);
void CkEmailW_SetHtmlBody(HCkEmailW cHandle, const wchar_t *html);
BOOL CkEmailW_SetMbHtmlBody(HCkEmailW cHandle, const wchar_t *charset, HCkByteData inData);
BOOL CkEmailW_SetMbPlainTextBody(HCkEmailW cHandle, const wchar_t *charset, HCkByteData inData);
BOOL CkEmailW_SetRelatedFilename(HCkEmailW cHandle, int index, const wchar_t *path);
BOOL CkEmailW_SetReplacePattern(HCkEmailW cHandle, const wchar_t *pattern, const wchar_t *replaceString);
BOOL CkEmailW_SetSigningCert(HCkEmailW cHandle, HCkCertW cert);
BOOL CkEmailW_SetSigningCert2(HCkEmailW cHandle, HCkCertW cert, HCkPrivateKeyW key);
void CkEmailW_SetTextBody(HCkEmailW cHandle, const wchar_t *bodyText, const wchar_t *contentType);
BOOL CkEmailW_UidlEquals(HCkEmailW cHandle, HCkEmailW e);
void CkEmailW_UnSpamify(HCkEmailW cHandle);
BOOL CkEmailW_UnpackHtml(HCkEmailW cHandle, const wchar_t *unpackDir, const wchar_t *htmlFilename, const wchar_t *partsSubdir);
BOOL CkEmailW_UnzipAttachments(HCkEmailW cHandle);
BOOL CkEmailW_UseCertVault(HCkEmailW cHandle, HCkXmlCertVaultW vault);
BOOL CkEmailW_ZipAttachments(HCkEmailW cHandle, const wchar_t *zipFilename);
#endif
