--- Makefile	2019-07-13 13:50:05.000000000 -0400
+++ Makefile	2019-10-28 13:31:36.918640240 -0400
@@ -15,10 +15,10 @@
 SHELL=/bin/sh

 # To assist in cross-compiling
-CC=gcc
-AR=ar
-RANLIB=ranlib
-LDFLAGS=
+# CC=gcc
+# AR=ar
+# RANLIB=ranlib
+# LDFLAGS=

 BIGFILES=-D_FILE_OFFSET_BITS=64
 CFLAGS=-Wall -Winline -O2 -g $(BIGFILES)
