// Copyright (c) 2009-2010 Satoshi Nakamoto
// Copyright (c) 2009-2021 The Bitcoin Core developers
// Copyright (c) 2014-2026 The Gridcoin developers
// Distributed under the MIT software license, see the accompanying
// file COPYING or https://opensource.org/licenses/mit-license.php.

#ifndef BITCOIN_VALIDATIONINTERFACE_H
#define BITCOIN_VALIDATIONINTERFACE_H

#include "fwd.h"

#include <functional>
#include <memory>

class CBlock;
class CBlockIndex;
class CBlockLocator;
class CScheduler;
class CValidationInterface;
struct MainSignalsInstance;
enum class MemPoolRemovalReason;

/** Register subscriber to receive updates from validation and mempool.
 *
 * Ordering requirement: the CMainSignals internals are created by
 * GetMainSignals().RegisterBackgroundSignalScheduler(), called once in AppInit2 after
 * g_scheduler exists. Registering (or unregistering) a subscriber BEFORE that call -- or
 * AFTER UnregisterBackgroundSignalScheduler() at shutdown -- is a silent no-op: the
 * subscriber is never connected and receives no callbacks. Always register subscribers
 * after the background signal scheduler has been wired. */
void RegisterValidationInterface(CValidationInterface* callbacks);
/** Unregister a subscriber previously registered with RegisterValidationInterface. */
void UnregisterValidationInterface(CValidationInterface* callbacks);
/** Unregister all subscribers. */
void UnregisterAllValidationInterfaces();

/**
 * Pushes a function to callback onto the notification queue, guaranteeing any
 * callbacks generated prior to now are finished when the function is called.
 *
 * Be careful to ensure no locks are held when calling this. The background
 * queue runs on the g_scheduler thread (see RegisterBackgroundSignalScheduler).
 */
void CallFunctionInValidationInterfaceQueue(std::function<void()> func);
/**
 * Blocks the current thread until the validation interface queue has caught up
 * with everything that was added before this call.
 */
void SyncWithValidationInterfaceQueue();

/**
 * Implement this to subscribe to events generated in validation and mempool.
 *
 * Each CValidationInterface() subscriber will receive event callbacks in the
 * order in which the events were generated by validation. Furthermore, each
 * subscriber may assume that callbacks effectively run in a single thread with
 * single-threaded memory consistency.
 *
 * Note: these signals are currently emitted SYNCHRONOUSLY on the thread that
 * triggered the event (typically while cs_main is held). This preserves the
 * canonical cs_main -> signals -> cs_wallet lock order and the
 * EXCLUSIVE_LOCKS_REQUIRED(cs_main) contract of the wallet callbacks. The
 * g_scheduler-backed background queue (RegisterBackgroundSignalScheduler) is
 * wired for CallFunctionInValidationInterfaceQueue and a future async switch.
 */
class CValidationInterface {
protected:
    /**
     * Protected destructor so that instances can only be deleted by derived
     * classes. If that restriction is no longer desired, this should be made
     * public and virtual.
     */
    ~CValidationInterface() = default;

    /**
     * Notifies listeners when the block chain tip advances.
     */
    virtual void UpdatedBlockTip(const CBlockIndex* pindexNew, const CBlockIndex* pindexFork, bool fInitialDownload) {}

    /** Notifies listeners of a transaction having been added to mempool. */
    virtual void TransactionAddedToMempool(const CTransactionRef& tx) {}

    /** Notifies listeners of a transaction leaving mempool. */
    virtual void TransactionRemovedFromMempool(const CTransactionRef& tx, MemPoolRemovalReason reason) {}

    /** Notifies listeners of a block being connected to the active chain. */
    virtual void BlockConnected(const CBlock& block, int height) {}

    /** Notifies listeners of a block being disconnected from the active chain. */
    virtual void BlockDisconnected(const CBlock& block, int height) {}

    /**
     * Notifies listeners that the active-chain best block was flushed, supplying
     * a locator the subscriber can persist to recover its position on restart.
     */
    virtual void ChainStateFlushed(const CBlockLocator& locator) {}

    friend class CMainSignals;
    friend struct MainSignalsInstance;
};

class CMainSignals {
private:
    std::unique_ptr<MainSignalsInstance> m_internals;

    friend void ::RegisterValidationInterface(CValidationInterface*);
    friend void ::UnregisterValidationInterface(CValidationInterface*);
    friend void ::UnregisterAllValidationInterfaces();
    friend void ::CallFunctionInValidationInterfaceQueue(std::function<void()> func);

public:
    CMainSignals();
    ~CMainSignals();

    /** Register a CScheduler to give callbacks which should run in the background (may only be called once). */
    void RegisterBackgroundSignalScheduler(CScheduler& scheduler);
    /** Unregister a CScheduler from giving callbacks; any pending background callbacks will be dropped. */
    void UnregisterBackgroundSignalScheduler();
    /** Call any remaining callbacks on the calling thread. */
    void FlushBackgroundCallbacks();

    size_t CallbacksPending();

    void UpdatedBlockTip(const CBlockIndex*, const CBlockIndex*, bool fInitialDownload);
    void TransactionAddedToMempool(const CTransactionRef&);
    void TransactionRemovedFromMempool(const CTransactionRef&, MemPoolRemovalReason);
    void BlockConnected(const CBlock&, int height);
    void BlockDisconnected(const CBlock&, int height);
    void ChainStateFlushed(const CBlockLocator&);
};

/** This will have its internals registered with a background signal scheduler in AppInit2. */
CMainSignals& GetMainSignals();

#endif // BITCOIN_VALIDATIONINTERFACE_H
